### ISSUE TITLE
No "B2G Desktop" Menu entries after installing on Windows

### ISSUE THREAD

**Issue by ghtomcat** [mozilla/r2d2b2g#10]
Windows 7 x64, Firefox 15.01

Happy to debug

**Comment by mykmelez** [comment]
Hi ghtomcat, thanks for the report! What menu entries do you see in the Tools menu after installing on Windows? And did the firstrun page open after installation?

**Comment by ghtomcat** [comment]
I saw the firstrun page after installation. I don't really have a Tools Menu on Firefox 15/Windows ...

**Comment by mykmelez** [comment]
The Tools menu (and the entire menubar) is actually present, it's just hidden by default. If you hold down the `Alt` key and press the `T` key, it should appear! And the B2G Desktop item should be in it.

But keep in mind that B2G Desktop will still crash on startup because of [bug 795484](https://bugzilla.mozilla.org/show_bug.cgi?id=795484).

**Comment by ghtomcat** [comment]
Thanks, new to me :) Maybe add a pointer for other n00bs like me?

**Comment by mykmelez** [comment]
Good idea! Reopening on making this clearer.

**Comment by mykmelez** [comment]
Hmm, rather than merely documenting the problem, we're going to fix the problem for real by adding an item to the unified Firefox menu on Windows/Linux, per issue #31!
