### ISSUE TITLE
Pressing home takes to a blank home screen in linux.

### ISSUE THREAD

**Issue by jaydeepw** [mozilla/r2d2b2g#11]
If I open some app, pressing ESC does not close the app.
I had also experienced this in B2G build for desktop that I had downloaded sometime back from Mozilla's FTP.

   If I open some app and press home screen, I goto blank home screen where I do not
see any icons. The screen shot has been attached below.

OS: Kubuntu-32bit (Linux)
Screenshot: http://i.imgur.com/8r1JX.png

**Comment by mykmelez** [comment]
The ESC issue turns out to be that B2G has removed the Back action (and its accompanying ESC keyboard shortcut; issue #13 is about changing the help text to reflect this). I'm not sure why going Home returns you to a blank homescreen, though. Which app were you in when you went home, and if you click and drag, does the homescreen do anything?

**Comment by jaydeepw** [comment]
I had opened firefox and dialer for which pressing Home button on the keyboard returned me a blank home screen.
I tried clicking, dragging and playing some more with the home screen, but expected home screen did not show up until I restarted the emulator.

**Comment by mykmelez** [comment]
I'm seeing this too on both 32-bit and 64-bit versions of Linux. Feels like something we should try to fix for v1.

**Comment by mykmelez** [comment]
It looks like this is [B2G bug 789399](https://bugzilla.mozilla.org/show_bug.cgi?id=789399), which appears to be fixed in the latest nightly builds. I'll push new builds of r2d2b2g with this version of B2G on Wednesday, so check back then for updated builds that no longer exhibit this problem!
