### ISSUE TITLE
Why did you deleted our posts ?

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#119]
I downloaded your emulator... on the download page it says : 
"Then try it out and report issues in our 'issue tracker'"

.... Because i Tracked 10 bugs in 10 minutes? 10 Bugs that should not appear on that stage of developpment?

!YOU! Asked us some feedback, we gave it to you... With screenshot and stuff.... and you deleted all?

Mozilla looks more like google days after days...

**Comment by fwenzel** [comment]
What are you talking about? https://github.com/mozilla/r2d2b2g/issues?state=open

**Comment by mykmelez** [comment]
Shinilol: I'm unaware of any deleted posts, neither yours nor anyone else's.

I did delete one comment of yours that reported an unrelated problem in an issue you filed about something else, since each report should represent a single issue.

And I have closed most of your reports, because they are reporting issues in Firefox OS itself, whereas this issue tracker is just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).

And read [Mozilla Forum Etiquette](http://www.mozilla.org/about/forums/etiquette.html), whose principles, like "be civil", govern communication on this issue tracker.
