### ISSUE TITLE
Uploading a file via input[type="file"] crashes the app

### ISSUE THREAD

**Issue by operatorjen** [mozilla/r2d2b2g#129]
I was trying to upload using a file input and upon submission it crashes the app and I have to reload it from the start.

**Comment by mykmelez** [comment]
Urk, how did we lose track of this? Sorry, @ednapiranha. :-(

If it isn't too much trouble, can you provide more info about which file input you were using (i.e. which app you were using, and what you were doing in the app)? It would also be handy to know which operating system you are using the Simulator on.

**Comment by operatorjen** [comment]
sure! Using OSX 10.7.5 and using <input type="file">

Testing it on my app at http://roller.noodletalk.org

If you sign in w/ Persona and then click on the camera icon, it'll trigger the browse file window from a file input trigger. At that point, the Simulator crashes.

**Comment by mykmelez** [comment]
Urk, an urgent project pulled me away from this (and all other Simulator issues, sadly) yet again, but after testing on the latest preview release, I don't see a crash, and my picture is properly posted to the stream that Roller presents to me; so perhaps the bug has been fixed in the meantime. Is there any chance you can try reproducing on the latest preview release?

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by operatorjen** [comment]
Yep just tested - seems to trigger the input file correctly (loads the file browsing window), but now I've run into another problem (I'll file a separate bug). When using FormData() in an ajax post request, it doesn't seem to post correctly.
