### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by MiguelSchneider** [mozilla/r2d2b2g#141]
Would it be possible to get automatic updates of the newest versions (including Gaia) on the simulator?

**Comment by tofumatt** [comment]
Automatic updates would be bandwidth-intensive and frequent, so for people on slow/limited connections it might be a PITA.

Having the latest version is nice though. Any way we can ask on first run?
- tofumatt | http://tofumatt.com

**Comment by MiguelSchneider** [comment]
Currently updates are triggered by the user in the device: A notification in the toolbar informs the user that and update is available, and the user has to click on the message to actually download the update. Hence, the frequency depends on the user (and he is well aware of it) and that some bandwidth will be used in the process.

Gaia & Gecko are changing (and improving a lot) every new build, and the simulator already has a very "old" version of Firefox OS. Simulator users might get a wrong idea as time passes and the gap between the simulator's and official build widens, and developers might get frustrated to develop apps which will not run on the device in the same way they did on the simulator. Hence, I think that some kind of update should be provided.

**Comment by mykmelez** [comment]
Once we start distributing the Simulator on AMO, users will automatically be updated the the latest version of the Simulator each time we ship a new version. And new versions of the Simulator will come with updated versions of B2G and Gaia.

We don't intend to ship updates of the B2G/Gaia components separately from updates of the addon as a whole, however, because doing so significantly complicates the user experience of the Simulator. The simplicity of installation and update is a key feature of the product, and we don't want to do anything to undermine it.

We do, however, intend to ship frequent updates and keep the B2G/Gaia components relatively up-to-date. Currently, version 0.8 of the Simulator, which shipped last Wednesday, November 21, is using B2G/Gaia components from the previous week, around November 14-15, based on the _aurora_ branch of B2G and the _nightly_ branch of Gaia.

**Comment by mykmelez** [comment]
On December 5, we shipped Simulator 1.0 from AMO, and users now get new versions automatically. So when we ship 1.1 next month, users will get it without having to check for an update manually.
