### ISSUE TITLE
WebGL not present

### ISSUE THREAD

**Issue by pyalot** [mozilla/r2d2b2g#143]
### Steps to reproduce
1. Visit http://get.webgl.com/
### Error observed

> WebGL: Can't get a usable WebGL context
### System information
- Firefox 16.0.2
- lsb_release -a:
  - Distributor ID: Ubuntu
  - Description:    Ubuntu 12.04.1 LTS
  - Release:    12.04
  - Codename:   precise
- uname -a: Linux wintermute 3.2.0-32-generic-pae #51-Ubuntu SMP Wed Sep 26 21:54:23 UTC 2012 i686 i686 i386 GNU/Linux
- cat /proc/driver/nvidia/version:
  - NVRM version: NVIDIA UNIX x86 Kernel Module  304.64  Tue Oct 30 11:09:29 PDT 2012
  - GCC version:  gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
- lspci -v | grep -i vga: 01:00.0 VGA compatible controller: NVIDIA Corporation GF104 [GeForce GTX 460](rev a1) (prog-if 00 [VGA controller])

**Comment by digitarald** [comment]
@pyalot is WebGL working fine on your Desktop Firefox?

**Comment by pyalot** [comment]
@digitarald Yes, webgl works in desktop firefox and chrome.

**Comment by mykmelez** [comment]
@pyalot: I've been thinking about this issue on and off since you filed it, but I haven't yet come up with any good theory for why it's happening. The desktop web runtime also had some problems with WebGL, like bugs [749459](https://bugzilla.mozilla.org/show_bug.cgi?id=749459) and [760323](https://bugzilla.mozilla.org/show_bug.cgi?id=760323), but those were fixed a while ago (in Firefoxes 15 and 16, respectively); and in any case they were mostly Windows-specific (one also affected Android).

**Comment by nickdesaulniers** [comment]
@pyalot WFM, can you verify with the most up to date build of the addon for [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)?

**Comment by mykmelez** [comment]
Closing this due to lack of needed info. But please do reopen if you can provide that info!
