### ISSUE TITLE
Blank screen (with mozilla logo) on start: libmozgnome.so missing

### ISSUE THREAD

**Issue by SkaveRat** [mozilla/r2d2b2g#170]
When I boot up the simulator, I only get a black screen with the mozilla logo.

I the console several errors appear:

Error: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIXPCComponents_Utils.import]
Source File: file:///[MYHOME]/.mozilla/firefox/bl756enl.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux64/b2g/components/HealthReportService.js
Line: 10

Error: TypeError: bluetooth is undefined
Source File: app://system.gaiamobile.org/js/bluetooth.js
Line: 35

Error: TypeError: bluetooth is undefined
Source File: app://system.gaiamobile.org/js/bluetooth.js
Line: 35

System: Arch Linux 64bit

**Comment by mykmelez** [comment]
Those console errors are probably unrelated. What version of the Simulator are you using?

**Comment by SkaveRat** [comment]
the one released after fix for #105

v1.0 released 1.12.

**Comment by mykmelez** [comment]
And where do you see the message "libmozgnome.so missing"?

**Comment by SkaveRat** [comment]
It shows up when launching the simulator with console on.

Interestingly enough: I now can launch the simulator successfully. haven't tried in the last couple of days. Maybe firefox just wanted a relaunch.

The mozlib errormessage is still there, but is an info now, not an error. Very strange.

**Comment by mykmelez** [comment]
Hmm, interesting. I'm not sure what was happening, but I'm glad to hear it's working for you!

In the past, one cause of this problem was that B2G would try to register a listener on localhost port 9999, and if something was already listening on that port, B2G would hang waiting for the port to become available.

But we fixed that by disabling the listener registration in the Simulator (and B2G developers later removed the listener registration entirely), so that shouldn't cause the problem.

But B2G does also register a listener on port 6000 to enable remote debugging. I suppose it's possible that the port 6000 listener has the same problem the port 9999 listener had when port 6000 is busy. So that might be the cause of the problem (and the reason it works now is that whatever was listening on that port is no longer running).

In any case, please reopen if it reoccurs so we can continue troubleshooting and try to track down the cause of the problem!
