### ISSUE TITLE
Crash while viewing source.

### ISSUE THREAD

**Issue by brendandahl** [mozilla/r2d2b2g#171]
To reproduce:

1) Open firefox os simulator with the console open.
2) Click on any of the source file links in the console.
3) Firefox os crashes

Tested OSX, FF OS Simulator 1.0

**Comment by mykmelez** [comment]
Does it happen consistently for you?

I don't see quite this behavior, as clicking on a source link opens the file in question in a new window for me. But after I opened three such windows, I clicked on one of the menus in the menubar, and B2G then crashed. Unfortunately, I haven't been able to reproduce the problem. Perhaps the protocol matters? I clicked on file:, resource: (which resolved to jar:file:) and app: links.

Sadly, the crash reporter won't be much help, because of [bug 785698](https://bugzilla.mozilla.org/show_bug.cgi?id=785698). We'll need to use a debug build of B2G to get a stack.

**Comment by brendandahl** [comment]
It happens to me every time on any protocol.  It doesn't crash right away, usually I have to leave the source window open for a few seconds then it crashes.  @digitarald was also able to reproduce when I saw him last Friday.

**Comment by dr-impossible** [comment]
I'm having this issue as well. Also using OS X and FF Simulator 1.0.

**Comment by mykmelez** [comment]
I can still reproduce, and not only after viewing source; B2G also crashes when I context-click on a message in the console (although that could be a different crash).

I suspect the ultimate solution will be to get rid of the Error Console in favor of the Web Console (for app developers) and the new Browser Console (for Simulator developers).

**Comment by nickdesaulniers** [comment]
So now the error console has been removed, you can connect to an app and clicking on the source line for any entry in the log takes you to the source in the debugger, no crash!
