### ISSUE TITLE
Problem Using Content Security Policy in manifest.webapp

### ISSUE THREAD

**Issue by palmagro** [mozilla/r2d2b2g#176]
Hi all, 

Im implementing a webapp for FirefoxOS and now im trying to test it in r2d2b2g but im having some troubles:

My app ask for Ajax jsonp request to a external server to get data, i.e:

$.ajax({
    dataType: "jsonp",
    url: "http://externalurl.com"
...
});

I tried to allow them through the manifest file, using:

"csp":"default-src *;script-src externalurl.com; options eval-script inline-script;"

and lot of combinations of csp configuration but no one works, it seems like a problem between the schemes app and http.

Which is the best way to allow this kind of request in a FireFox OS App?

Thank you very much.

Pedro

**Comment by mykmelez** [comment]
It isn't clear how Firefox OS applies the CSP specified in the `csp` property of the manifest, but I bet it doesn't do it in the Simulator, because of the way the Simulator currently installs apps. We plan to fix that. But fixing it still won't solve your problem, because an app CSP can only restrict the CSP further (than the default CSP), it can't relax the CSP, per https://wiki.mozilla.org/Apps/Security and https://developer.mozilla.org/en-US/docs/Apps/Manifest#csp.

It is possible to relax the same-origin XHR restriction for a privileged app, but you have to specify the _system_ permission and then set some parameters in the XHR, per https://bugzilla.mozilla.org/show_bug.cgi?id=692677#c68. That still won't work in the Simulator today, because of the way the Simulator currently installs apps. But it will work in the future, once the Simulator installs apps in a way that causes Firefox OS to register their permissions.

**Comment by mykmelez** [comment]
Your other option would be to implement the app as a hosted app on the same server from which you are retrieving data.

This seems more like a support request than an issue report. And I hope I've been able to give you the information you requested! Even though the answer is unfortunately that the Simulator doesn't quite support your use case :-/

If you have any additional questions, I recommend asking them in the [dev-webapps discussion forum](http://www.mozilla.org/about/forums/#dev-webapps), where there are folks with lots of knowledge about Firefox OS's CSP and other app development topics.
