### ISSUE TITLE
simulator should exclude dev/test homescreen apps

### ISSUE THREAD

**Issue by jds2501** [mozilla/r2d2b2g#182]
When I tried out the FF OS simulator on the add-ons page, I noticed that the desktop build that was launched was an eng build. Eng builds are using meant for internal development on Gaia and Gecko only (very heavily used in automation), but doesn't really make a lot of sense to an end-user. The builds you actually want to grab are user builds.

The big check you determine to figure out if eng vs. user is to look and see if you have extra homescreen apps like test agent, ui tests, twitter share, etc. This does show up when I tried out the simulator.

**Comment by mykmelez** [comment]
The intended audience for Firefox OS Simulator is app developers, not end-users, so decisions to include/exclude apps should be based on whether or not they make sense to an app developer, not an end-user.

Nevertheless, a quick look at the apps in question (presumably the ones in _test_apps/_, although _twittershare_ is in _showcase_apps/_) suggests that none of them are particularly useful for app developers. Some might be good examples of how to build apps, but not as mere apps in the Simulator--we'd need to make their source code easily available.

So we should remove them from the Simulator.

The build in question here is the Gaia profile, and it looks like this is as simple as setting _GAIA_APP_SRCDIRS_ to `apps showcase_apps` (from its default value of `apps test_apps showcase_apps`). Gaia's _Makefile_ lets you do that by specifying it in a _local.mk_ file, but we can probably just set it in our _Makefile_, and that's probably better, since we'd have to maintain a branch to store a _local.mk_ file in the submodule directory for Gaia.

(We can also use _build/override-webapps.json_ to remove specific apps without removing a whole directory.)

**Comment by mykmelez** [comment]
Note that the [unagi](http://hg.mozilla.org/mozilla-central/annotate/9afad96e2b20/b2g/config/unagi/config.json) and [otoro](http://hg.mozilla.org/mozilla-central/annotate/9afad96e2b20/b2g/config/otoro/config.json) build configurations specify `VARIANT=user` to make user builds, but that variable appears to be handled by the build scripts for Gonk, not those for B2G Desktop, so it isn't usable for building B2G Desktop.

I'm not sure exactly what VARIANT configures; but it seems to do more than just specify apps. My local copy of the [_B2G_ repository](https://github.com/mozilla-b2g/B2G) has some build scripts that appear to have been generated by a build command I ran in it at some point and which contain configuration like:

```
# Target is secure in user builds.
ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=1
...
# Disable debugging in plain user builds.
enable_target_debugging :=
```

**Comment by mykmelez** [comment]
(Updated the title of the bug to focus on the apps we want to exclude, since there is no concept of VARIANT builds in B2G Desktop.)
