### ISSUE TITLE
Add title and icon to the simulator window

### ISSUE THREAD

**Issue by waldyrious** [mozilla/r2d2b2g#197]
The simulator window has no title so it shows up in the taskbar as "Untitled window" and with the default icon.

OS: Xubuntu 12.04
Firefox 17.0.1
Simulator Version 1.0

**Comment by ochameau** [comment]
Opened platform bug to fix that in b2g desktop:
  https://bugzilla.mozilla.org/show_bug.cgi?id=865210
We can also fix window title in desktop as well.

**Comment by ochameau** [comment]
I just submitted a patch to fix both the icon and title.

**Comment by mykmelez** [comment]
@ochameau I added the title to prosthesis in a03e47eca736bcf49e1d229dc4d5b7aa16978787, not just because @vingtetun doesn't want it in B2G, but also because adding it to B2G wouldn't actually add it to the Simulator, since the Simulator uses its own shell.xul, which is not merely a XUL overlay onto B2G's shell.xul but is rather a distinct XUL document that overrides B2G's version (although it reuses B2G's shell.js script).

I forget exactly why I went with an override instead of an overlay, but I think it had to do with a bug in the overlay approach, which I tried first. Or maybe it was just some limitation of overlays. In any case, the current approach works well, and shell.xul rarely changes in B2G (the last change on both the central and b2g18 branches was on October 31!), so our version doesn't tend to get out-of-date (although I just noticed that we should pick up that October 31 change, and I landed it in a2963bbc0122503113b7d91f8e8f97171ff4cd49).

Leaving this issue open pending resolution of the icon portion of the issue.

**Comment by mykmelez** [comment]
@vingtetun granted review on the patch in bug 865210. It hasn't landed yet, but I applied it to the b2g18 branch, rebuilt B2G with it, and then rebuilt the Simulator with the rebuilt B2G. So the latest preview release of the Simulator contains the change.

And it works on Windows and Linux. But on Mac the dock icon is still generic. So it looks like there is something more to do still.

Thus I'll leave the issue open. But I'll move it out of the v3 milestone, as we don't need an icon on Mac to ship v3!

**Comment by ochameau** [comment]
Ok, so if I understand correctly the state of this issue, we just have to fix the icon on Mac and we are done here?
I submitted a patch to fix that here: https://bugzilla.mozilla.org/show_bug.cgi?id=874459

**Comment by mykmelez** [comment]
> Ok, so if I understand correctly the state of this issue, we just have to fix the icon on Mac and we are done here?

Yup, that's the only thing left to do!

> I submitted a patch to fix that here: https://bugzilla.mozilla.org/show_bug.cgi?id=874459

Thanks, I'll build and test it!

**Comment by mykmelez** [comment]
Bug 874459 has now been fixed, and we've uplifted the fix to the b2g18 branch, and the latest preview build has it!
