### ISSUE TITLE
Error while loading localization file

### ISSUE THREAD

**Issue by tayloraswift** [mozilla/r2d2b2g#21]
When running FX Nightly from the terminal, I get this error on startup—

info: r2d2b2g: Error while loading localization: There is no localization file for your language.
info: r2d2b2g: linux/b2g/b2g-bin terminated with 0
Running global cleanup code from study base classes.

Nightly continues to function (more or less) normally, but Tools►B2G Desktop doesn't work.

I'm running 19.0a1 (2012-10-13), on Ubuntu 12.10 64-bit.

**Comment by fwenzel** [comment]
Possible problem with localized Firefox builds? @Kelvinsong which language is your Nightly build in?

**Comment by tayloraswift** [comment]
It's in English, web content goes: [en-us],[es],[en]

The build is downloaded straight from nightly.mozilla.org.

**Comment by mykmelez** [comment]
The localization message is probably Add-on SDK [bug 792837](https://bugzilla.mozilla.org/show_bug.cgi?id=792837), which has been fixed, but we haven't yet picked up the fix.

The menu item not working is [bug 776845](https://bugzilla.mozilla.org/show_bug.cgi?id=776845) (we don't yet support 64-bit Linux because there are no B2G Desktop builds for that platform).

**Comment by mykmelez** [comment]
We've since picked up the fix for the localization message, and we've landed support for 64-bit Linux, which will appear in tomorrow's builds. Please test those once they become available!
