### ISSUE TITLE
Dialer Pad not working

### ISSUE THREAD

**Issue by applecool** [mozilla/r2d2b2g#215]
The dialer pad on the firefox Simulator is not working! Even when you type the numbers through the keyboard, its not working. And even by pressing the keys on the dialer pad.

I use Mac OS X 10.8.2 Mountain Lion. (Firefox 17)

**Comment by mykmelez** [comment]
This is probably because the Simulator imperfectly simulates phone hardware. I see this error in the console when I open the dialer app:

> Timestamp: 2012-12-20 11:36:24 
> Error: TypeError: telephony is undefined
> Source File: app://communications.gaiamobile.org/dialer/js/dialer.js
> Line: 5

The manifest for the Dialer app [specifies a _dial_ activity](https://github.com/mozilla-b2g/gaia/blob/c4c912a7e5d2cb39bca3bfdb62ecc8545af0d8cf/apps/communications/manifest.webapp#L102), so it seems like the Simulator should support dialing, even if it just fakes it like the SMS app does via its [desktopTesting.js file](https://github.com/mozilla-b2g/gaia/blob/4a5062f7e84a583a09ec18cde0cdfcad244fa94c/apps/sms/js/desktopTesting.js), so app developers can test invoking the dialer from within their apps.

@digitarald What do you think?

**Comment by jaydeepw** [comment]
Hi, I can confirm this bug even in latest nightly as of the time of reporting this issue.
The nightly version is 21.0a1 (2013-02-08)

**Comment by mykmelez** [comment]
The dialer pad now works, although dialing still doesn't do anything. But simulating dialing is another issue, so we should track that separately.
