### ISSUE TITLE
Simulator hangs before going to the page linked by button

### ISSUE THREAD

**Issue by AprilMorone** [mozilla/r2d2b2g#216]
Simulator hangs before going to the page linked by button.  Also, I got error messages about that there is an illegal value that has been done.  That error message had appeared when the simulator had opened.  Also, when trying the simulator's keyboard, it didn't type anything.  The only way I could type anything into the simulator was to use my computer's keyboard.
Below are pictures of both the warning I'd gotten when the simulator opened, and of the Simulator window.

![FireFox OS Similator Error Message](https://f.cloud.github.com/assets/1834852/15239/8c56b13c-4718-11e2-8fd2-9bb717fe340b.jpg)
![FireFox OS Similator Error Proof](https://f.cloud.github.com/assets/1834852/15240/9af69554-4718-11e2-888c-65a8fc910019.jpg)

**Comment by mykmelez** [comment]
I'm sorry it isn't working for you, but thanks for reporting the problem! Those errors in the Error Console are probably not relevant (I've seen similar ones appear when the Simulator is working), but it's worrisome that you see a hang instead of the Firefox OS interface! What version of the Simulator are you running? And are you running any version of B2G Desktop at the same time by any chance?

**Comment by mykmelez** [comment]
Closing due to lack of info needed to investigate problem.
