### ISSUE TITLE
Keyboard in simulator not working

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#222]
When I tried to add a contact, I clicked on the name bar and the keyboard appeared, but when I clicked on a letter the keyboard disappeared.

**Comment by mykmelez** [comment]
This is fixed in the most recent preview builds of the next version of the Simulator ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).
