### ISSUE TITLE
Add packaged app from existing folder

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#25]
1. Click "Add from Folder" button
2. Select folder (or select *.webapp?)
3. App gets packaged and installed
4. Clicking "Update" repackages and installs the app

**Comment by mykmelez** [comment]
According to the [v1 spec](https://docs.google.com/document/d/1S538182p1zwCAFHvIRTYCu0LkdHLVh3KZCVhOdKbh1Q/edit), this should be an "Add App from Directory" button that "will launch a directory chooser and install that directory as a “packaged app”". So the file picker should direct users to select a folder/directory rather than a *.webapp file.

**Comment by digitarald** [comment]
We would need to validate if there is a manifest in that folder. So why not select the manifest right away? Add app by URL also wants a URL to a manifest. Seems more consistent.

It's easy to switch later, so I don't have a strong opinion on that at this point. Just seemed generally more straightforward when going through the 2 flows.

**Comment by digitarald** [comment]
Feature added in #38
