### ISSUE TITLE
Some notes/bugs

### ISSUE THREAD

**Issue by SimonKok** [mozilla/r2d2b2g#265]
The home button doesn't work in gallery, camera mode and when selecting a wallpaper.
When picking a new wallpaper, if you scroll through the wallpaper gallery by dragging the wallpapers up or down it doesn't stop dragging when you release the mouse.

Also, a scrollbar in the error console would be nice.

Platform: Windows 7 Ultimate x64
Firefox version: 18.0.1
Simulator version: 1.0

Thank you very much.

**Comment by mykmelez** [comment]
Thanks for the reports! But hmm, I can't reproduce the Home button issue. The button works for me in Gallery, Camera, and when selecting a wallpaper.

And I also can't reproduce the wallpaper gallery dragging issue, although I do see issue #239, which causes drags to turn into drag-and-drops.

But a scrollbar in the Error Console would definitely be nice! I filed issue #279 on that, since it's easier to track and resolve bugs when each one has its own issue in the tracker.

**Comment by SimonKok** [comment]
'which causes drags to turn into drag-and-drops', that was exactly what I meant. Thank you very much :)

**Comment by mykmelez** [comment]
Erm, I made a mistake when referencing issue #239. The actual issue I meant to reference is #166, which will translate mouse events into touch events, to better simulate interaction with interfaces like the wallpaper picker.
