### ISSUE TITLE
Simulator 2.0pre5: geolocation dialog throws "frame is null" error

### ISSUE THREAD

**Issue by jrburke** [mozilla/r2d2b2g#277]
Using the 2.0pre5 build at firefox hack day. It seems like maybe the build of gaia in that versoin has a bug with the geolocation prompt: user clicks Accept, but no geolocation callback occurs, and there is a "frame is null" error in the web console.

I expect it will be sorted out as gaia is updated, but just noting it, happy to retest when a new build is out.

**Comment by mykmelez** [comment]
The geolocation prompt seemed to work in earlier versions of Simulator, although only on some OSes. So this seems to have broken since then. Hopefully it'll get fixed in a newer version of Gaia, but if it's B2G Desktop-specific, then the Gaia developers probably aren't paying close attention to it, and we may have to figure it out ourselves.

**Comment by mykmelez** [comment]
@kanru has contributed a fake geolocation provider, which we can use to make geolocation work on all platforms. I added it to the Simulator in this branch:

https://github.com/mykmelez/r2d2b2g/tree/geolocation
https://github.com/mykmelez/r2d2b2g/blob/geolocation/prosthesis/components/FakeGeolocationProvider.js

However, it still needs some work. As I [discussed with @kanru on dev.webapps](https://groups.google.com/forum/#!topic/mozilla.dev.webapps/phGFqhXrP6A), we'll want an interface for developers to specify the location (with the default being the current location, as provided by Firefox). And some parameters for movement, although we could do that in a second phase of development.
