### ISSUE TITLE
Phone App

### ISSUE THREAD

**Issue by danPixl** [mozilla/r2d2b2g#300]
When you press a button, it does not register and appear in the box.

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS.

In any case, this problem seems to be fixed in the most recent preview builds of the next version of the Simulator ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).
