### ISSUE TITLE
When appcache fails to resolve, the installation fails silently (simulator only)

### ISSUE THREAD

**Issue by mattbasta** [mozilla/r2d2b2g#306]
If the "appcache_path" of the manifest points to an invalid appcache or an appcache which does not resolve (i.e.: a non-200 response), Firefox OS would otherwise throw an error. In the simulator, this error does not appear and the app installation silently fails.

**Comment by nickdesaulniers** [comment]
This may be because the simulator doesn't always have the latest builds of B2G and Gaia, so it wouldn't surprise me if we just happened to take a snapshot during a regression.  In the meanwhile, can you push a dummy branch of the app you were testing with the bad appcache and link it here, for testing?

**Comment by mattbasta** [comment]
You can just use something like this:

http://badappcache.testmanifest.com/manifest.webapp

**Comment by mykmelez** [comment]
Fixed by #523.
