### ISSUE TITLE
Packaged app install is completely broken

### ISSUE THREAD

**Issue by mattbasta** [mozilla/r2d2b2g#337]
Packaged apps can be installed from unagis but not the simulator.

See:

http://app-loader.appspot.com/4fca9

**Comment by nickdesaulniers** [comment]
For reference, this occurs when installing an app through the browser using window.navigator.mozApps.install.  This occurs in the current release build, with the error (see attached image).  Note: this appears fixed in a build of the current source, which has yet been pushed to release, I'll see if maybe this was fixed in a recent bug.
![Screen Shot 2013-03-01 at 2 07 09 PM](https://f.cloud.github.com/assets/1823839/211652/819e724a-82bc-11e2-87a9-cfcb452896dd.png)

**Comment by nickdesaulniers** [comment]
Also fixed in preview builds.  This will get fixed once preview becomes release.
