### ISSUE TITLE
Developer Toolbar > "firefoxos manager" command

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#34]
Per the [v1 spec](https://docs.google.com/document/d/1S538182p1zwCAFHvIRTYCu0LkdHLVh3KZCVhOdKbh1Q/edit), the Developer Toolbar should have a "firefoxos manager" command that opens the manager.

**Comment by digitarald** [comment]
Thinking about it (not knowing a lot of gcli philosophies), is there any reason why `firefoxos` shouldn't just launch the dashboard; without `manager`? cc @dangoor

**Comment by dangoor** [comment]
Good question. I'm not sure if commands with subcommands are able to just run on their own. @joewalker is the authoritative person on that. Being able to just type "firefoxos" to launch the manager does sound like a win, as long as you can still do "firefoxos <some subcommand>" as well

**Comment by joewalker** [comment]
GCLI doesn't currently allow executable parent commands, because parameters could be confusing. Is that string a parameter or an attempt at a sub-command?

I think we might allow parameterless parent commands in the future (and I raised [bug 807652](https://bugzilla.mozilla.org/show_bug.cgi?id=807652) for this) but it's not here now.

**Comment by dangoor** [comment]
Yeah, that makes sense. One thing also is that "firefoxos manager" as a command does not actually require typing that many characters.
