### ISSUE TITLE
Geolocation: Default to custom, not current, coordinates

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#356]
This will help the addon pass review, the user/developer has to opt in to sharing their geolocation coordinates with the addon.

**Comment by mykmelez** [comment]
Did some thinking on the way home, and here are my thoughts on implementation (for both this and issue #357):

Instead of passing it back to the shell, the geolocation dialog persists the type of geolocation to provide (default, current, or custom) in a preference, r2d2b2g.geolocation.type. It also stores a custom geolocation in two preferences, r2d2b2g.geolocation.custom.latitude and r2d2b2g.geolocation.custom.longitude (note: prefs can't contain floats, so the values must be stored as strings). The [&lt;prefwindow> XUL tag](https://developer.mozilla.org/en-US/docs/XUL/prefwindow), and its associated machinery for reflecting XUL form controls into prefs, is probably the best way to do this.

When FakeGeoPositionProvider is instantiated, it checks the value of r2d2b2g.geolocation.type. If the value is "default" or "custom", it does nothing (besides setting a pref observer; see below); but when its watch() method is called, it updates the callback with the default or custom geolocation. If the value is "current", however, it notifies "r2d2b2g-geolocation-observe".

Meanwhile, SimulatorActor has registered a listener for "r2d2b2g-geolocation-observe", and when it observes the notification, it requests the current geolocation from Firefox. Firefox then uses watchPosition to watch the geolocation and notifies SimulatorActor each time it changes; whereupon SimulatorActor notifies "r2d2b2g-geolocation-change"; which FakeGeoPositionProvider observes in order to update its callback.

Finally, when FakeGeoPositionProvider is instantiated, in addition to checking the value of r2d2b2g.geolocation.type, it sets a pref observer on the r2d2b2g.geolocation.\* branch. When one of the prefs change, it updates its callback with the new geolocation. If r2d2b2g.geolocation.type changes to "current", then it notifies "r2d2b2g-geolocation-observe" to start observing current geolocation changes. If, however, it changes _from_ "current" to "default" or "custom", then it notifies "r2d2b2g-geolocation-ignore", which SimulatorActor observes in order to tell Firefox to stop watching the geolocation.

So Firefox only watches the geolocation while the pref is set to "current" _and_ the fake provider is instantiated.

As a beneficial side-effect, the value of the prefs persist across sessions, so users who set a custom geolocation don't have to reset it after restarting the Simulator.

(Side note: I wonder why we call it FakeGeoPositionProvider instead of FakeGeolocationProvider. Perhaps we should change it.)

**Comment by mykmelez** [comment]
Clearing assignee until @nickdesaulniers has time to look at this again, in case someone else wants to pick it up!

Also, note that @rpl modified the workflow in #436, so the workflow I described earlier in this issue may no longer be relevant.

**Comment by mykmelez** [comment]
Fixed by #446.
