### ISSUE TITLE
simulate Bluetooth connection

### ISSUE THREAD

**Issue by ghazel** [mozilla/r2d2b2g#393]
The Simulator should simulate a Bluetooth connection, so developers can test apps that use Bluetooth to communicate with Bluetooth devices.

**Comment by mykmelez** [comment]
Unfortunately, the Simulator doesn't yet simulate bluetooth connections, so it isn't possible to use it to connect to a bluetooth device. Nevertheless, it should be! I'll modify this issue's title/description to turn this into a feature request for a bluetooth simulation.

**Comment by qdot** [comment]
Hi. Member of the FxOS bluetooth team here.

Unfortunately BT under r2d2b2g is not gonna be possible for the moment. Bluetooth /only/ works on the phone right now, and simulating it isn't something we can polyfill because BT relies on things like the kernel being able to open sockets to pipe audio over, as well as some fairly complex protocol work that currently happens in C++.

**Comment by mykmelez** [comment]
Thanks @qdot. Since it isn't possible, I'm going to close this issue until such time as it becomes possible. In the meantime, @wbamberg's [new docs on MDN](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator) note that it isn't supported.

**Comment by ghazel** [comment]
Guys -- I never asked for simulator support or simulation of a Bluetooth connection. My original issue title and description was changed.

My initial request was about Bluetooth connections on real phones. How do you form RFCOMM connections? We have an app that runs on Android phones, and we'd love to port it over, but it requires RFCOMM connections between devices.

**Comment by qdot** [comment]
Hi greg! I've been meaning to email you for a while, heh. 

We currently don't have raw bluetooth socket access available in B2G. The only features we're shipping in V1.0 are HFP and OPP based file transfer, both of which we provide managed APIs to and only allow verified apps to get at. I think we may be adding A2DP and AVRCP for v1.1, but once again, those will still be managed APIs. We are certainly considering exposing raw bluetooth to the system, but only in a v1.2+ timeframe.

**Comment by mykmelez** [comment]
Ah, sorry @ghazel for misunderstanding your request! In any case, I'm glad that @qdot was able to answer your question.

**Comment by iFadey** [comment]
From above discussion, I understood it's not simulated yet. I am building an app that require client/server kind of communication using Bluetooth API. Again from the discussion, Kyle mentioned RFCOMM is not supported which I know can provide client/server kind of two-way communication.

I have three questions:

1) Is there an alternate to RFCOMM in Firefox OS which can help us develop same kind of client/server functionality where client initiate the request and server listening for requests responds to it?

2) For testing Bluetooth API I am using Geeksphone Keon. Is there a way to use developer tools to debug app running on real device?

3) How can I test the end-to-end functionality because simulator don't support Bluetooth API. Kindly suggest a way for end-to-end testing.

**Comment by qdot** [comment]
Currently, there's no way for non-certified apps (certified apps are signed and usually ship with the phone os) to access Bluetooth. While that's slated to change at some point in the future, it's not in the timeline before v1.2, which is as far out as we have scheduled at the moment. There's also no API available to do what you're looking for yet, though once again, that functionality is planned for some point in the future. I recommend watching the B2G:Bluetooth component on bugzilla if you want specific updates for when features might become available.

**Comment by iFadey** [comment]
Ok thanks for the info :)
