### ISSUE TITLE
Push to device doesn't work

### ISSUE THREAD

**Issue by slerknes** [mozilla/r2d2b2g#408]
Push to device tends to not work when I try to Push applications to my Geeksphone Peak. It has worked a couple of times, which makes me wonder what the problem may be. Remote debugging mode is enabled, and I am using Firefox OS Simulator v3 on Ubuntu 12.10

**Comment by mykmelez** [comment]
Push To Device is still under development, and it's a complex feature, so it may well have bugs! And we're pushing improvements to it with every preview build, of which the last one was published on Wednesday, April 3.

Since it's worked a couple of times, I'll assume you've successfully configured your computer (per [Using Hardware Devices](https://developer.android.com/tools/device.html)) and device (checking "remote debugging").

There's a known B2G issue ([bug 848957](https://bugzilla.mozilla.org/show_bug.cgi?id=848957)) that checking "remote debugging" doesn't always seem to work. When I've encountered that issue, toggling the checkbox a few times (ending with it checked, of course) seems to fix the problem.

There are also bugs that affect behavior under certain conditions, like [bug 842725](https://bugzilla.mozilla.org/show_bug.cgi?id=842725), which was only fixed about a month ago. Depending on the version of B2G on your phone, it may still have that and other bugs.

Finally, I recently noticed that restarting adb on your computer after connecting to the device will prevent adb from reconnecting to the device until either "remote debugging" is toggled or the USB cable is unplugged/replugged. And the Simulator restarts adb each time you start Firefox (in the latest preview build, it waits until you open the Dashboard the first time to do this).

So if you previously started adb (either on your own, from the command-line, or by starting a previous session of Firefox), then you should toggle "remote debugging" or unplug/replug the USB cable _after opening the Dashboard_.

Let me know if any of this helps; otherwise, please provide some additional info to help us diagnose the problem! In particular, it would be useful to know the version of B2G running on the phone (Settings > Device information > Software and Settings > Device information > More Information > Build Identifier, Git commit info) and the version of the Simulator you're using (Tools > Add-ons > Extensions).

I would also be interested to hear about any messages you see in the Error Console (and the terminal, if you start Firefox from a command line) after you use about:config to set the `extensions.r2d2b2g@mozilla.org.sdk.console.logLevel` preference to the integer value `0` (zero).

**Comment by nickdesaulniers** [comment]
I just verified push to device to a Geeksphone Peak from OSX.  I would recommend double checking ADB in Linux, since it is a little more involved to get it working within Linux.

Also, really old builds on device have adb, but not the webapp actors, which could be why a device would appear but push would fail.

**Comment by mykmelez** [comment]
@Pawzter Have you had better luck lately, and was any of the provided information helpful? Just trying to get a sense of whether this is still a problem for you. Also, if you haven't done so, I recommend updating to either the [latest stable release](https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/) or the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).

**Comment by Kontrolloren** [comment]
Hi, this is the user formerly known as Pawzter. I managed to sort out my problems on Linux by adding a line to "/etc/udev/rules.d/51-android.rules" with the idVendor 05c6. Afaik there has not been published any documentation on how to to this, which seems to be necessary to debug apps on the GeeksPhone Peak. If anyone else thinks that this is needed, i could publish a short guide on how to do it.

I am in the progress of making a alternative update mechanism to make things even easier, which can be found at https://github.com/Kontrolloren/Firefox-OS-LAN-App-Publisher

**Comment by mykmelez** [comment]
> Afaik there has not been published any documentation on how to to this, which seems to be necessary to debug apps on the GeeksPhone Peak. If anyone else thinks that this is needed, i could publish a short guide on how to do it.

@wbamberg documented this in the [Simulator docs](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator), but please do add any additional information that would help developers like you get things working!

> I am in the progress of making a alternative update mechanism to make things even easier, which can be found at https://github.com/Kontrolloren/Firefox-OS-LAN-App-Publisher

That's an interesting idea, and I like that it bypasses adb and its configuration challenges. Still, I suspect it'll still be easier for a developer to push their app from their desktop than to pull it from their device, once adb is configured.

Nevertheless, I wonder if there's a way to use this concept to expose an app installation service on the device that the Simulator can connect to as a client!
