### ISSUE TITLE
Emulator : Make a screenshot

### ISSUE THREAD

**Issue by Progi1984** [mozilla/r2d2b2g#421]
A feature which will be interesting in the emulator will be the availability to make a screenshot of the current state of the emulator.

**Comment by Gioyik** [comment]
You can do it, try with the buttom home + end at the same time. It will take you a screenshot.

**Comment by Progi1984** [comment]
Perfect :)

But no way to remove the button bar in the bottom ?

**Comment by Gioyik** [comment]
Buttom bar in the bottom? Could you be more speciffic or possibly show me a screenshot?

**Comment by Progi1984** [comment]
Like this one : 
![2013-04-18-22-14-11](https://f.cloud.github.com/assets/1533248/399054/fa236454-a865-11e2-9d9e-1004f7373d3e.png)

**Comment by Gioyik** [comment]
It's possible but i am not sure why you like remove it. However if you think that is a good function remove this bar and good to be added in the next version of the simulator, please fill other bug.

I think that the main problem (take a screenshot) in this bug was solved, so, if you have other problems or you have a suggestion, please open other issue.

Solved @mykmelez :)

**Comment by Progi1984** [comment]
Yep, exactly.

I close and open an another bug.

Thanks @Gioyik !
