### ISSUE TITLE
reload app in single step from within Simulator

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#422]
It should be possible to reload an app in a single step from within the Simulator after making some changes to it, just like it's possible to reload a web page in the browser via View > Reload and the Ctrl/Cmd-R keyboard shortcut.

For a hosted app, this would just reinstall and then restart the app. For a packaged app, it would first repackage the app before reinstalling and restarting it.

The interface to the feature can be identical to the one in the browser: a View > Reload menuitem paired with a Ctrl/Cmd-R keyboard shortcut. And the implementation can use the remote debugging channel to trigger the reload, sending a message to the client (i.e. the Firefox addon) requesting that it do the same thing it does when the developer presses the Update button for an app in the Dashboard.

Then the developer will be able to go directly back and forth between their code editor and the Simulator without having to visit the Dashboard each time they make a change.

**Comment by nickdesaulniers** [comment]
+1

**Comment by rpl** [comment]
+1 +prototype :-)

**Comment by nickdesaulniers** [comment]
Hey, awesome to see this land in 3.0pre6!  What a nice feature!

One of the things I'm currently working on is using this [new tool](https://marketplace-dev.allizom.org/developers/test/receipts/) to install a hosted app with a valid verifiable receipt.  This requires me to host my app I'm developing behind a domain.  While I develop, I have to push my changes to my remote machine.  Then I have to close down the app and restart it.  The command+r hotkey doesn't work because hosted apps installed from the browser in the sim aren't registered in the dashboard.

I figured I'd share what I was trying to do, so we could together discuss possible solutions.

**Comment by mykmelez** [comment]
@nickdesaulniers I filed issue #443 on a solution to your problem. Please comment there about whether or not it would solve your problem!
