### ISSUE TITLE
"App Download Stopped"

### ISSUE THREAD

**Issue by Progi1984** [mozilla/r2d2b2g#424]
After some mails with marketplace-developer-support@mozilla.org, we have found a bug.

I use the emulator in version 2.0.1, with Firefox 20.0 et Windows 8 x64.

When i download from the marketplace a package application (and not hosted apps), i have an error : 
![bug](https://f.cloud.github.com/assets/1533248/369103/3141417c-a2d0-11e2-9400-92a05cd55ba2.jpg)
**in the marketplace**

```
    FFHelios Download Stopped
```

**in the console log**

```
    Content JS INFO at app://system.gaiamobile.org/js/app_install_manager.jsh:188 in ai_handleDownloadError: downloadError event, error code is INVALID_SIGNATURE
```

I test with some applications : 
- the mine : https://marketplace.firefox.com/app/ffhelios/?src=mkt-search
- and some others
  - https://marketplace.firefox.com/app/here-maps-packaged
  - https://marketplace.firefox.com/app/math-game
  - https://marketplace.firefox.com/app/game-pack

**Comment by rpl** [comment]
it looks like a b2g issue, and probably it's already fixed because I've
just tried
on Simulator 3.0pre6dev and ffhelios install and run correctly.

Could you retry on a recent simulator build?
- Windows:
  https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi
- Mac: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi
- Linux:
  https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi

**Comment by Progi1984** [comment]
Yep, perfect, that solves my bug. Thanks for your help.
