### ISSUE TITLE
can't find Addon when 'History' is set to ' Never remember history' in preferences

### ISSUE THREAD

**Issue by jincreator** [mozilla/r2d2b2g#431]
seperate from #385 because it's absolutely different bug
### details

I have problem find Addon at Nightly 22.0a1(not nightly anymore) + FxOS Simulator 3.0pre4.
I'm now using 23.0a1 + FxOs Simulator 3.0pre6 and still confirm this issue, but seems only me.
I use Firefox with 'Never remember history' and when I change preference and restart, I can see Addon back.

It's hard to find people who set preference like me, so it makes hard to find what makes this bug.
Also I guess this bug will happen in Aurora 22, but didn't test it.

**Comment by mykmelez** [comment]
I see this problem with the latest nightly and the latest preview build (3.0pre6). When I set extensions.logging.enabled to true and restart Firefox from the command line, the following shows up in the terminal:

```
*** LOG addons.xpi: startup
*** LOG addons.xpi: Skipping unavailable install location app-system-share
*** LOG addons.xpi: checkForChanges
*** LOG addons.xpi: No changes found
*** LOG addons.xpi: Loading bootstrap scope from /Users/myk/deleteme/extensions/r2d2b2g@mozilla.org
*** LOG addons.xpi: Calling bootstrap method startup on r2d2b2g@mozilla.org version 3.0pre6
```

But Tools > Web Developer > Firefox OS Simulator is missing. If I load Dashboard directly by entering its URL (resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html) into the location bar, the page loads, so the addon is clearly installed. But the page is broken, presumably because it can't communicate with the main module, because the main module never loaded.

Disabling and reenabling the addon via the Add-ons Manager doesn't make a difference, nor does removing it and then undoing the remove.

Another SDK-based addon, @bgirard's [Gecko Profiler](https://github.com/bgirard/Gecko-Profiler-Addon) ([XPI](https://github.com/bgirard/Gecko-Profiler-Addon/raw/master/geckoprofiler.xpi)), doesn't have the same problem, although it looks like he's using SDK 1.13.2, while the Simulator uses 1.14.

@ochameau: have you heard anyone else report this with an SDK-based addon?

**Comment by ochameau** [comment]
Oh! So what happens is that when you set this setting, Firefox always start is private browsing mode.
And menuitems library is following jetpack guidelines and only add items in non-private windows...

I think that it would just be simplied to give simulator the private browsing permission...
I submitted a patch to do this in PR #541.
