### ISSUE TITLE
refresh hosted app that wasn't installed by Dashboard

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#443]
If a hosted app wasn't installed by the Dashboard, the Simulator should still have enough information about the app to reinstall and restart it, so it should do so when the user selects Refresh. That way a user who installs a hosted app directly in the Simulator, for whatever reason (f.e. @nickdesaulniers's [test app with receipt use case](https://github.com/mozilla/r2d2b2g/issues/422#issuecomment-16589426)), can use Refresh to refresh it!

@rpl What do you think?

**Comment by mykmelez** [comment]
FWIW, it should be possible to refresh a directly-installed packaged app this way as well, although it would be a lower priority to make that work, since we don't have a specific use case for it (generally speaking, users might want to try installing apps on the Simulator via the Marketplace or their own server to test out the end-to-end process of installing and using an app).

**Comment by nickdesaulniers** [comment]
Users won't be able to install packaged apps from their own site because packaged apps need to be signed.  Theoretically, a user could sign with their own certificate and use a custom build of the simulator with a custom build of gaia with their cert, but that's rather impractical.

But if a user installs a packaged app from the marketplace, it wont show up in the dashboard.
