### ISSUE TITLE
Error when loading new url into simulator page

### ISSUE THREAD

**Issue by jeffgca** [mozilla/r2d2b2g#448]
If I open the app manager, then paste a new url into the location bar I see this traceback:

Timestamp: 2013-04-19 8:27:45 AM
Error: r2d2b2g: An exception occurred.
Traceback (most recent call last):
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/tabs/tab-firefox.js", line 69, in _onReady
this._emit(EVENTS.ready.name, this._public);
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 123, in _emit
return this._emitOnObject.apply(this, args);
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 153, in _emitOnObject
listener.apply(targetObj, params);
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/windows/tabs-firefox.js", line 110, in _emitEvent
tabs._emit(type, tab);
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 123, in _emit
return this._emitOnObject.apply(this, args);
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 153, in _emitOnObject
listener.apply(targetObj, params);
File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/main.js", line 924, in
simulator.sendListTabs();
File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/main.js", line 587, in simulator.sendListTabs
list: tabs
File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/content/worker.js", line 351, in postMessage
throw new Error(ERR_FROZEN);
Error: The page is currently hidden and can no longer be used until it is visible again.

**Comment by mykmelez** [comment]
Oof, I see that too. We experimented with using _addon-page_ to hide the top chrome, including the location bar, to make the Dashboard look more like part of the application's interface than a web page (à la Add-ons Manager), which would reduce the risk of this happening.

But it stopped working when we moved the location of the Dashboard's HTML file in the addon source; and it exhibited other problems (lots of ["can't access dead object" errors](https://github.com/mozilla/r2d2b2g/issues/search?q=dead+object), which may or may not have caused bugs; plus a problem I noticed a couple times where the top chrome would go away for every tab until I restarted Firefox). So I recently removed it.

And it wouldn't completely solve the problem anyway, since you can navigate to another page even on a tab with no top chrome: just select File > Open Location or type its keyboard shortcut, and Firefox will open a modal dialog soliciting a location. So even if we start using an updated addon-page, this can still be a problem.

And the bug is probably in the addon's code, which seems to be trying to access the Dashboard page after it has been frozen in the bfcache by a navigation away from it. Perhaps the APIs we're using are handing us a footgun, in which case we might file an enhancement request against the SDK once we figure out the specific issue and identify a better alternative. But regardless, our addon code should not be accessing the Dashboard page unless it is currently loaded in a tab and steaming hot (or at least thawed)!

**Comment by jeffgca** [comment]
@mykmelez / @ochameau  if there are key things we need to build in Jetpack to help with this, please file bugs and cc me. I makes me sad Add-on Page hasn't gotten the love it needs to be useful, but I'm also unsure a content page is the right answer for the app manager, as opposed to a separate window?

**Comment by ochameau** [comment]
I think we are missing listeners for pagehide/pageshow here:
  https://github.com/mozilla/r2d2b2g/blob/master/addon/lib/simulator.js#L115-L118

Otherwise, I've already seen some report of the painfullness of workers going to the bfcache. I think that adding an attribute to know if a worker is reachable (not ready yet, destroyed or in bfcache) would help and also, eventually remove the exception, or replace it by a warning, or just ignore the message being sent... That sounds errorprone, but the feedback I received about exception vs warning vs just ignored is controversial:
  https://bugzilla.mozilla.org/show_bug.cgi?id=847309#c6
  https://bugzilla.mozilla.org/show_bug.cgi?id=693345#c34

**Comment by mykmelez** [comment]
@canuckistani: @ochameau and I have discussed the relative merits of implementing the App Manager as a page versus a tab in the Developer Toolbox. And @tsmuse has begun designing integration of Dev Kit functionality into the Simulator, including a mockup of some minor changes to the Simulator Dashboard in [bug 858277](https://bugzilla.mozilla.org/show_bug.cgi?id=858277) along with an idea for a permanent sidebar in [bug 858282](https://bugzilla.mozilla.org/show_bug.cgi?id=858282).

My short take: the App Manager belongs in a page or other non-tab/page-centric interface rather than the Developer Toolbox, because the toolbox is tab/page-centric (i.e. it gives you functionality scoped to a particular tab/page), whereas the manager is a non-tab/page-centric view of your apps in development and their status on multiple targets (Firefox itself, the Simulator, a Firefox OS device, an Android device running Fennec).

Thus it is more akin to the Add-ons Manager than tools like the Inspector and Debugger. Except that it is intended for developers, not users, so the menu item for accessing it belongs in the Web Developer submenu instead of the main Tools menu. Although we might add more immediately-accessible access points: a keyboard shortcut, a toolbar button.

@ochameau has a somewhat different take, which you can read about in [this developer-tools thread](https://groups.google.com/forum/?fromgroups=#!topic/mozilla.dev.developer-tools/sqI4K5sOZhw). But we both agree that we could really use UX input, so I've begun reaching out to the UX team about it. I also think Product input would be handy, and I would be happy to get it from you and other Product folks!

**Comment by jeffgca** [comment]
@mykmelez Bill and I also struggled with this when discussing use cases last week. I agree that the UI should not be in the current devtools toolbox, so our choices are a discrete page or a discrete tab, or possibly both? I might be tempted to advocate both because I think the small-screen laptop use case might be better with a tab whereas a multi-monitor set-up might lend itself to having a discrete window.

One additional wrinkle, IIRC the browser debugger currently launched in its own process; we could provide a unified experience attached to that separate process including the app manager and other remote-capable tools.  Curious what you and @ochameau think about that.

**Comment by mykmelez** [comment]
Fixed by #454.

> @mykmelez Bill and I also struggled with this when discussing use cases last week. I agree that the UI should not be in the current devtools toolbox, so our choices are a discrete page or a discrete tab, or possibly both? I might be tempted to advocate both because I think the small-screen laptop use case might be better with a tab whereas a multi-monitor set-up might lend itself to having a discrete window.

The toolbox has both "bottom bar" and "separate window" modes.

Generally speaking, I imagine that the toolbox's bottom bar mode is there because it puts the toolbox as close as possible to its target (i.e. the page being developed) to minimize the effort required to switch between them. And the separate window mode is available both because some developers prefer it (perhaps because it maximizes the real estate available to the target within its window) and because the bottom bar mode doesn't make sense for a remote target.

But the factors seem different for the app manager. It doesn't seem like users will go back and forth between the manager and a target the way to do with the toolbox. Perhaps they'll do so to push an app to a physical device repeatedly. At least as that feature is currently implemented. But it seems like we should build that functionality into the toolbox, such that one opens the toolbox for an app running on a device and then pushes the app to the device via the toolbox (which then reattaches itself to the app after pushing it and restarting it).

So my initial instinct is that the app manager wouldn't benefit from multiple modes.

> One additional wrinkle, IIRC the browser debugger currently launched in its own process; we could provide a unified experience attached to that separate process including the app manager and other remote-capable tools. Curious what you and @ochameau think about that.

I think the browser debugger is in a separate process so it can survive that process (and thus help debug/profile startup/shutdown). The app manager's doesn't need that, though. So it seems unnecessary. Unsure whether it would nevertheless benefit from being a part of that window in the user's mental model. I suspect not, since the browser debugger is for browser developers, while the app manager is for app developers.
