### ISSUE TITLE
Can't use geolocation API in web app

### ISSUE THREAD

**Issue by wbamberg** [mozilla/r2d2b2g#450]
When I use the geolocation API in the Simulator, I get an error like this:

```
Content JS LOG at app://27e5aa93-1c75-4e41-920f-9a6695f1a592/scripts/whereami.js:13 in error: 1 : undefined
```

This is "Permission denied" according to https://developer.mozilla.org/en-US/docs/DOM/window.navigator.geolocation.getCurrentPosition#PositionError. But I (think I) am correctly requesting the geolocation permission in my manifest, and the Simulator does not give me any warnings about the manifest having problems. 

An example web app that gives me this error is here: https://github.com/wbamberg/simulator/tree/master/example-apps/whereami-simplest and the slightly more interesting version I want to end up with is here: https://github.com/wbamberg/simulator/tree/master/example-apps/whereami. Both of these work fine in Firefox.

It's more than possible that I'm doing something foolish here :).

**Comment by mykmelez** [comment]
@wbamberg Are you using the stable release of the Simulator by any chance? That version doesn't yet have geolocation support. But the latest preview build does ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)). And when I test whereami-simplest in the preview build, it works fine.

Specifically, I did:
- git clone git://github.com/wbamberg/simulator.git ~/Mozilla/wbamberg-simulator
- open Dashboard, press Add Directory, choose ~/Mozilla/wbamberg-simulator/example-apps/whereami-simplest/manifest.webapp
- in Where am I? app press Where am I? button
- press Allow when Gaia prompts me to allow app to know my location

Results: my coordinates appear (37.38838440000001, -122.0826074).

One possible thing that can go wrong is that Firefox might not be able to determine your geolocation. To confirm, try running the [MDN geolocation example](https://developer.mozilla.org/en-US/docs/WebAPI/Using_geolocation?redirectlocale=en-US&redirectslug=Using_geolocation#Live_Result) in Firefox. If it works, then it should work in the Simulator too.

We also fixed a geolocation bug in the latest preview build, 3.0pre6, which I pushed on Wednesday, so if you have an earlier preview build, then you should get the latest.

And you might try setting a custom geolocation to see if that makes any difference. To do so, press the Pin button on the toolbar in the Simulator, use the Geolocation dialog to specify a custom geolocation, and then try your app again.

**Comment by mykmelez** [comment]
Also cc: @nickdesaulniers, who implemented geolocation support, and @rpl who recently improved it, in case they have insight.

**Comment by wbamberg** [comment]
I was definitely using the pre-release of the Simulator (3.0pre6) (I know this because I tried setting a custom location using the toolbar button), and Firefox could determine the position. But the mere act of you looking at the example apparently caused it to start working again.

So I suppose this is invalid, and I'm sorry for wasting your time, as well as confused.

**Comment by mykmelez** [comment]
No worries! Who knows, maybe there's a bug here somewhere, and we just haven't figured out what it is yet. In any case, please reopen the issue if you experience the problem again!

**Comment by mykmelez** [comment]
One issue that has tripped up a few developers is that an app has to pre-request the geolocation permission in its manifest. This can be unexpected for two reasons:
1. a regular web page in Firefox doesn't need to pre-request permission to use geolocation (although Firefox still asks the user to confirm the request);
2. a webapp didn't need to pre-request permission in the original security model, and the requirement was added relatively recently.

So I can imagine a scenario in which:
- a developer creates an app that uses geolocation without pre-requesting it;
- the app doesn't work, so the developer refers to the docs and learns about the requirement;
- the developer adds the permission to their manifest but doesn't update the app in the Simulator (either because they don't realize they must do so or simply forget);
- the developer tests the app, and it still doesn't work, because the Simulator hasn't been updated with the version of the app that pre-requests the permission.

I'm not saying that's what happened to you, just hypothesizing. ;-)

**Comment by mykmelez** [comment]
But even if it isn't what happened to you, it suggests that the Simulator should monitor source files, including but not limited to the manifest; and if one of them changes, the Simulator should subtly notify the developer that the app is out-of-date and give them a happy path for updating it. I have opened issue #451 on that.
