### ISSUE TITLE
Make bundled adb play nicely with running system ADB

### ISSUE THREAD

**Issue by potch** [mozilla/r2d2b2g#464]
When I start up the simulator, I run into issues where the device isn't seen, or my resident adb will no longer see connected devices. I believe they are fighting for the same ports/residency on my system. We should investigate how to either
- use a running ADB daemon, or
- possibly start on a different port (I don't know whether this is possible)

**Comment by mykmelez** [comment]
It's a little scary to think of using a running ADB daemon, since it might not be the same version. But it's a bad user experience to kill that daemon in favor of our own, since the user probably started it for a reason. And we also don't want to get into daemon killing wars with some other process (or the user, if the user is flipping back and forth between the command line and the Simulator). So yes, let's reuse the existing daemon or start on a different port if possible.

**Comment by bkase** [comment]
It seems like while it's possible to start adb on a different port, by default, adbd on the phones communicate over the default port (and this can't be changed without root). I'm looking into reusing the running daemon now.

**Comment by ochameau** [comment]
Hey, you may have seen @canuckistani message on dev-developer-tools about ADB chrome plugin.
There is some interesting facts here. They are doing something very similar to us.
At first sight, I thought they were compiling their C++ plugin with adb as shared library, but no, they end up calling a shell script that itself launches adb !!! adb executable is shipped in their addon.
Still we may look around this project to see if we can learn interesting tricks, like this one:
  https://github.com/repenaxa/ADBPlugin/blob/master/ADBPluginAPI.cpp

Otherwise, I'm wondering if loading adb dynamic libraries with jsctype would be a good option to improve our adb support? The adb zip on windows has two dll files, so it can be easy to call internal adb method if it exposes a C API.
