### ISSUE TITLE
Simulator not being able to install App,error->badParameterType:missing directory /tmp/b2g

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#472]
I am currently running Firefox 19 and i have added the simulator as an add-on.When i try to install a App,an error pops displaying:
badParametertype:missing directory /tmp/b2g/{bunch-of-characters which changes everytime i try to install it again}

**Comment by mykmelez** [comment]
Hi @SoumenG, I'm sorry to hear you're having this problem! Some additional information will help us diagnose it. Which version of the Simulator are you using, and which OS are you using it on? Also, does this happen with every app or only certain ones?

If you're using the stable release (2.0.1), you might try the latest preview build of the next version ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)). I'm also curious to know whether you're able to create a directory in the /tmp directory. Can you open a terminal window and issue the command `mkdir /tmp/testdir` successfully?

**Comment by ghost** [comment]
I am running Simulator version 3.0pre4 on  fedora17 and yes,it does show this error everytime i try to install an Application.
I am able to create a directory in /tmp alright.
Looking forward to your reply.

**Comment by mykmelez** [comment]
Please try installing the latest preview build, 3.0pre8, and let me know if you still experience the problem!

**Comment by novia713** [comment]
im having the same issue with r2d2b2g 3.0pre8 in Fedora 18 with Firefox 2.0. see screenshot → http://imm.io/14C4a  it occurs every time i click "run" a packaged app of my own

**Comment by nickdesaulniers** [comment]
@SoumenG emailed me asking to be assigned this.  I'd recommend starting out looking in addon/lib/simulator.js.  You can see [here](https://github.com/mozilla/r2d2b2g/blob/6f2c8f172e7a47e9f88ba60d60c059bf47bed7ca/addon/lib/simulator.js#L305) is where we try to create that folder.

[tempdir](https://github.com/mozilla/r2d2b2g/blob/6f2c8f172e7a47e9f88ba60d60c059bf47bed7ca/addon/lib/simulator.js#L303) is defined [here](https://github.com/mozilla/r2d2b2g/blob/6f2c8f172e7a47e9f88ba60d60c059bf47bed7ca/addon/lib/simulator.js#L210).

Getters in JavaScript were added in [1.8.1](https://developer.mozilla.org/en-US/docs/JavaScript/Guide/Working_with_Objects?redirectlocale=en-US&redirectslug=Core_JavaScript_1.5_Guide%2FWorking_with_Objects#Defining_getters_and_setters) may seem intimidating at first but they are literally just a way of wrapping functionality around property access (syntactic sugar).

The random bunch of numbers are indeed random!  Each app needs to be uniquely identifiable.  As you can see, the origin is of the form [app://uuid](https://github.com/mozilla/r2d2b2g/blob/6f2c8f172e7a47e9f88ba60d60c059bf47bed7ca/addon/lib/simulator.js#L283).

**Comment by rpl** [comment]
@mykmelez @nickdesaulniers I haven't a Fedora to give it a try, but it's possible that Firefox Desktop installed from yum is built/configured to use a different
temporary dir (named "TmpD" in the xpcom service) from b2g-desktop packaged inside the simulator addon:

e.g.
- Firefox Desktop: "TmpD" -> /var/tmp
- B2G Desktop: "TmpD" -> /tmp

@SoumenG could you try this small firefox addon http://ubik.cc/projects/firefox-display-tmpd.xpi
to check where your Firefox Desktop's "TmpD" is pointing to?

![firefox-display-tmpd](https://f.cloud.github.com/assets/11484/460234/ef5ec284-b418-11e2-9e84-e8f1052ce8cf.png)

**Comment by ghost** [comment]
@rpl @mykmelez @nickdesaulniers 
It does use a different temp directory -> /var/tmp.But does this issue reproduce for every system running fedora?I guess fedora/yum's default config builts firefox in  /var/tmp.So,b2g has to be configured to use the default directory as used by firefox.

**Comment by ghost** [comment]
@rpl Could we use a symlink to /var/tmp/b2g in /tmp?

**Comment by marienfressinaud** [comment]
@SoumenG > Yes, it works with a symbolic link from /tmp/b2g to /var/tmp/b2g :) thanks for idea!

**Comment by ghost** [comment]
version 4.0pre2dev solves this issue.

**Comment by mykmelez** [comment]
> version 4.0pre2dev solves this issue.

I still see this in my Fedora 17 installation.

[SpecialSystemDirectory.cpp](https://github.com/mozilla/mozilla-central/blob/168c667d3da30cba186fe25be13190591d48f108/xpcom/io/SpecialSystemDirectory.cpp#L584-L596), which determines the temp dir for Firefox, looks for the _TMPDIR_, _TMP_, and _TEMP_ environment variables on Unix, falling back to `/tmp/` if none of those are defined. And the /usr/bin/firefox Bash script sets _TMPDIR_ to `/var/tmp` in Fedora. So Fedora's Firefox uses that directory as its temp dir.

But the Simulator addon doesn't pass through that environment variable when it starts the Simulator, so the Simulator uses `/tmp/` as its temp dir. Which is where the [webapps actor's install method](https://github.com/mozilla/r2d2b2g/blob/bf924acf11c28c8c24dba770ca821adc57efffa5/prosthesis/content/dbg-webapps-actors.js#L216-L225) looks for an app that the addon tells it to install.

Perhaps the best fix is to pass the actor a path instead of just an ID, so the actor and the addon don't have to share an understanding of where apps will be located in preparation for installing them. But an easier and adequate fix would be to pass through _TMPDIR_ if it's defined when starting the Simulator process on Linux.

The addon starts the Simulator in [addon/lib/remote-simulator-client.js](https://github.com/mozilla/r2d2b2g/blob/6d2b02252b55acd17485457e45cdfbd2438ba1ff/addon/lib/remote-simulator-client.js#L165-L190). It uses the [subprocess module](https://github.com/mykmelez/jetpack-subprocess/blob/master/lib/subprocess.js), and the docs embedded in that module explain how to specify an environment variable when spawning a subprocess.

So the fix would be to set the _TMPDIR_ variable for the Simulator subprocess to the value of `Services.dirsvc.get("TmpD", Ci.nsIFile).path` (making remote-simulator-client.js import Services in the process, just like [simulator.js does](https://github.com/mozilla/r2d2b2g/blob/6f2c8f172e7a47e9f88ba60d60c059bf47bed7ca/addon/lib/simulator.js#L37)) whenever _Runtime.OS_ is whatever it is on Linux—which looks like "Linux", according to the [system/runtime module](https://addons.mozilla.org/en-US/developers/docs/sdk/latest/modules/sdk/system/runtime.html).

**Comment by mykmelez** [comment]
Fixed by @SoumenG in #516, which will make it into the next preview build. Thanks @SoumenG!
