### ISSUE TITLE
experimental banner renders horizontally on Linux and Windows

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#49]
The diagonal "experimental" banner in the top-left corner of the page renders horizontally underneath the FxOS Simulator header on Linux and Windows. It should render diagonally on those OSes, just as it does on Mac.

**Comment by digitarald** [comment]
I'd guess we can remove it; I only threw it in to make the new UI more HTML5-ish.

**Comment by mykmelez** [comment]
I'm not so sure we should remove it. The addon is still immature, and the software it bundles (B2G and Gaia) is itself in an alpha-ish stage of development (the B2G builds we bundle are from the "aurora" branch).

Perhaps _experimental_ is not quite the right word, but it does seem useful to identify the product as being in an early stage of development, to help set people's expectations. Websites and packaged software use _alpha_, _beta_, _preview_, _early preview_, _preview release_ and similar terms/phrases to signify this.

@dangoor: what do you think?

(Aside: I'd love to see a ["Fork me on GitHub" ribbon](https://github.com/blog/273-github-ribbons) in the top-right corner to attract contributors, but perhaps that isn't appropriate, and it's certainly a different issue.)

(Aside: what's the best way to attach a screenshot to a GitHub issue? I have one for this bug.)

**Comment by dangoor** [comment]
I think that calling it "alpha" rather than "experimental" at this stage makes sense. If we call it "aurora", that may just get confusing since aurora is not a general industry term in the way "alpha" is.

"Fork me on GitHub" is usually great in project web pages, but I don't think I'd want to see that in an actual user interface.

I think you need to upload the screenshot to somewhere else that you can link to. Kind of irritating. If you're on a Mac, you can probably use Skitch and then go through some sort of Evernote sharing dance (haven't tried this). You can probably also toss it into Dropbox and link to it there. Otherwise, there's twitpic and imgur and sites like that... I wish I had a "best practice" to point you to!
