### ISSUE TITLE
Include more languages from gaia-l10n repository

### ISSUE THREAD

**Issue by flodolo** [mozilla/r2d2b2g#490]
Current version (3.0) of Firefox OS Emulator add-on includes only 10 languages. Would it be possible to include more languages from https://hg.mozilla.org/gaia-l10n/?

This add-on would be a great tool to help localizers testing their localization.

**Comment by mykmelez** [comment]
I just posted to the original thread in dev-l10n about this. Here's what I said:

On 2013/05/03 02:03, Axel Hecht wrote:

> Yeah, github issue would be right. Myk is the guy driving the addon. 

And I'm subscribed to this list! So I'm happy to chat here in addition to responding to GitHub issues.

I did recently add six more locales to the Simulator, which added about half a megabyte to the package size. And I'm not necessarily opposed to adding more. But I'm concerned about making the addon even larger, since it's already very large, and we've been trying to make it smaller.

> That said, I'm not sure how much that wins you, I don't think that addon updates as frequently as your localizations do? 

Typically, I push a preview build containing the latest development changes once per week. But sometimes I skip a week or two, or I skip updating Gaia. So preview builds with updated versions of Gaia can come out less frequently.

Release builds come out every 1-3 months.

> Asking everybody using that addon for developing apps to update every day or two doesn't sound very compelling.
> 
> On the other hand, if one/two/three of you would maintain a l10n-focused version, that might be more like it? Different addon-id, more granular version numbers, different update url would be my thought ad-hoc.
> 
> And then figure out how to make that publish often. 

This is a great idea! And last month I did some work to making building the Simulator with additional locales much easier. Here's a description of the process for building with Gaia's "all languages" file and then packaging your build for distribution to others:

  https://github.com/mozilla/r2d2b2g/issues/124#issuecomment-17420895

It's pretty straightforward, and it works on all three primary OSes! (Use MozillaBuild on Windows.) Plus it doesn't actually require a compiler, as there's no actual compilation (the process uses pre-compiled builds of B2G Desktop). So it's worth setting up regular builds for localizers. And I'm happy to answer questions and troubleshoot problems as you do so!

**Comment by mykmelez** [comment]
So, having said all that: I think it'd be more valuable to first explore setting up localizer builds of the Simulator on a regular basis. Then, if we run into roadblocks that we can't resolve, we can consider adding more locales to the main builds as a second-best option.

**Comment by flodolo** [comment]
Thanks, I'll look into the process and see what I can get out of it.

**Comment by suoko** [comment]
Do you know if adding new languages via ' plugins' as in ff browser is feasable with ffos?
That would be awesome and unique if compared to other mobile os'

**Comment by mykmelez** [comment]
@flodolo has been working on l10n builds, so I'm going to close this issue for now in favor of that approach. We can always reopen it and reconsider it if that approach proves to be unfeasible.

> Do you know if adding new languages via ' plugins' as in ff browser is feasable with ffos?
> That would be awesome and unique if compared to other mobile os'

Hmm, I don't know if language packs are feasible. You might try asking in the [dev-b2g](http://www.mozilla.org/about/forums/#dev-b2g) or [dev-gaia](http://www.mozilla.org/about/forums/#dev-gaia) forums!
