### ISSUE TITLE
Scrollbars repaint incorrectly on Firefox OS Simulator, on Ubuntu 13.04

### ISSUE THREAD

**Issue by dholbert** [mozilla/r2d2b2g#495]
STR:
1. Start up Firefox OS Simulator. (I'm using 3.0 on Ubuntu 13.04 64-bit)
2. Launch settings app.
3. Scroll. (either with mousewheel, or click-and-fling)

ACTUAL RESULTS: The scrollbar repaints incorrectly, as you scroll. (until it starts to fade away, after about a second, at which point it's fully repainted correctly)

Basically, it looks like we're not invalidating enough of the scrollbar. We _are_ invalidating the newly-covered-by-scrollbar and the no-longer-covered-by-scrollbar regions -- but we're apparently not invalidating the still-covered-by-scollbar-but-now-covered-by-a-different-looking-part-of-the-scrollbar. 

This might be an underlying gecko bug, but I've only seen it in Firefox OS simulator so far, so I'm filing it here to start.
Screenshot:
![broken-scrollbar-screenshot](https://f.cloud.github.com/assets/426803/461761/64ababf8-b449-11e2-9d69-527182b456c1.png)

**Comment by dholbert** [comment]
Screencast: https://people.mozilla.com/~dholbert/screenshots/scrollbar-bug.ogv

**Comment by mykmelez** [comment]
The Simulator used to apply the B2G stylesheet to all frames. Now it applies them only to content frames, which includes Gaia's system app, its homescreen app, and all other Gaia apps (along with third-party apps) but does not include the XUL shell that surrounds them all.

So if the problem occurs only on the Simulator, and it doesn't occur in B2G Desktop, then that might be the reason.

**Comment by dholbert** [comment]
In the latest B2G desktop build ( https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/2013-05-03-03-10-34-mozilla-central/b2g-23.0a1.multi.linux-x86_64.tar.bz2 ), I don't see any scrollbars at all, actually. (Tried both the Settings and the Browser apps.)  (to be clear: I can scroll, but there's just no visible scrollbar.)

So: assuming that the above-linked b2g desktop build is otherwise mostly comparable to the Firefox OS simulator's build (I don't know), then yeah, this appears to be a simulator-specific issue.

**Comment by mykmelez** [comment]
It isn't quite comparable, as the Simulator is using a build from the B2G18 branch, but the scrollbar style looks the same on the two branches:

http://mxr.mozilla.org/mozilla-b2g18/source/b2g/chrome/content/content.css#8
http://mxr.mozilla.org/mozilla-central/source/b2g/chrome/content/content.css#8

And it hides XUL scrollbars in XUL. Which explains why you don't see them in B2G Desktop, and why you do see them in the Simulator: the Simulator doesn't apply that stylesheet to the XUL "shell" window.

And that's generally a good idea, because that stylesheet removes a lot of default XUL style that we want for the Simulator's shell. But we probably don't want those scrollbars and should remove them.
