### ISSUE TITLE
Pushing to device doesn't work with Firefox Nightly or Aurora and FirefoxOS master gaia/master gecko on Windows 7

### ISSUE THREAD

**Issue by Cwiiis** [mozilla/r2d2b2g#538]
I assume this feature should normally work, so I'm not sure what part of my configuration is causing it not to work.

The device is detected fine and I can use the Android SDK's adb to communicate with it correctly, push and pull from it, use the shell, etc. The add-on detects its presence correctly when I unplug and plug in the device. When I press the 'Push' button on any of my apps, however, it does nothing. There is no feedback to say that the clicking did anything either, and no error messages.

I've tried this with both Firefox Aurora and Firefox Nightly, on Windows 7 64-bit, with the same result. My phone is a Geeksphone Peak running my own b2g build from master (both gecko and gaia) a couple of days old.

**Comment by Cwiiis** [comment]
Just confirmed that the bundled adb in the add-on works correctly too, both pushing and pulling.

**Comment by Cwiiis** [comment]
On the exact same machine, using the simulator in Linux (Fedora 18 64-bit) inside a VM, pushing works (but for whatever reason, installing apps on the simulator is broken...)

**Comment by mykmelez** [comment]
Hmm, I'm not sure what's going on here. Let's try making the addon log more messages about its behavior.

To do that, use about:config to create the integer preference _extensions.r2d2b2g@mozilla.org.sdk.console.logLevel_, set it to the value 0 (zero), and then use the Add-ons Manager to disable/reenable the addon. Then try pushing again and see if any relevant messages appear in the Error Console. You might want to press the Errors and Messages buttons in the console to exclude warnings, since the Dashboard's version of jQuery generates a lot of warnings that clutter up the console.

**Comment by freshteapot** [comment]
At the Oslo Firefox Os day we had on the saturday just gone.
- I have a "peak" running:

gecko:
master from "mozilla-central".
changeset:   133008:28c185bcc46a

gaia:
38ce0068bad14e27b42b9b3800ade592f1b9c9f4

FirefoxAurora:
23.02A.
- I have the logs enabled as your request above.

![screen shot 2013-05-27 at 3 16 30 am](https://f.cloud.github.com/assets/305673/566102/41f792c8-c66b-11e2-9d67-c4fa5681050e.png)

**Comment by flaki** [comment]
**Ignore the error below...**
_...turns out I did not do my homework of configuring the device. The app seems to successfully push and install on the device (it, however is not installed as an icon on the home screen, which might as well be a FirefoxOS/PEAK firmware bug)._

**I still have the opinion, however, that failing the push without any user feedback is a big no-no, and should be fixed.**

> Happens here too, clicking the "push" button, the command fails "silently" - no result or error message presented to the user. Setting up the loglevel as above produces the attached log. adb fails with "info: r2d2b2g: adb: Error: insufficient permissions for device" error.
> 
> My main concern here is not simply that the push fails, but it does so without any apparent feedback to the user of the failure or its cause.
> 
> Phone is a PEAK w/latest stock FW.
> Sim version is latest nightly (4.03pre), firefox is recent nightly, also (24.0a1 (2013-05-23)) running on Ubuntu 13.04/64bit.
> ![screenshot from 2013-05-29 02 41 54](https://f.cloud.github.com/assets/2089432/576258/dbd4e8ac-c7f9-11e2-8ae7-46d3300ded00.png)

**Comment by mykmelez** [comment]
@Cwiiis Were you able to get it working? If not, you might try the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)), which includes some ADB fixes.

@freshteapot It looks like ADB successfully detected your device and the addon started the process of pushing to it. I'd need to see additional logs from below the point where the screenshot cuts off in order to know where things went wrong, though.

@flaki wrote:

> ...turns out I did not do my homework of configuring the device. The app seems to successfully push and install on the device (it, however is not installed as an icon on the home screen, which might as well be a FirefoxOS/PEAK firmware bug).

That sounds like #452, which is actually a bug in B2G itself.

> I still have the opinion, however, that failing the push without any user feedback is a big no-no, and should be fixed.

I agree! I filed #593 on doing so.

**Comment by mykmelez** [comment]
Folks, I'm going to close this issue, as we haven't heard from y'all in a while. But please reopen if you're still experiencing the problem!
