### ISSUE TITLE
'badParameterType' when trying to install/update app on Fedora 18, Firefox 20

### ISSUE THREAD

**Issue by Cwiiis** [mozilla/r2d2b2g#539]
Every time I try to install or update an application, I get the error "badParameterType: missing directory /tmp/b2g/xxxx", where xxxx is, I assume, a uuid. Afterwards, the application is not installed on the simulator. Thankfully, pushing to a real device works :)

**Comment by mykmelez** [comment]
@Cwiiis That sounds like issue #472, which should be fixed in the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).
