### ISSUE TITLE
FirefoxOs simulator not rendering css properly

### ISSUE THREAD

**Issue by Trux** [mozilla/r2d2b2g#558]
The simulator seems to overide the custom css file.

Tested with firefox 21 and Aurora under Windows 7 and OS X v10.8
![ffox](https://f.cloud.github.com/assets/1033424/555866/6724724a-c3c9-11e2-888e-359eed8965a2.png)

**Comment by mykmelez** [comment]
The Simulator does apply some default style to content. And there is an issue with that style (with a fix in #550). But I'm not sure that's the issue here. It's hard to say without access to your app. Is it a hosted app (or a packaged app whose source is available) by any chance?

cc: @ochameau

**Comment by Trux** [comment]
It's a packaged app mostly empty for the moment. 
You can check the html/css here https://github.com/Trux/FoxTimelapse

**Comment by ochameau** [comment]
Here the simulator actually simulate Firefox OS behavior!
Some custom CSS rules are applied on various HTML elements in order to make them look native to the targeted OS.
We do that on Fennec and FirefoxOS.
It is currently quite hard to debug these issues as we do not have nor the inspector, nor the style sheet helper devtools working, but it should be more obvious when we get them. You will be able to see the platform CSS rules being applied and be able to know which rule you will need to overload.
If you are interested in knowing more, these css are defined here:
  http://mxr.mozilla.org/mozilla-central/source/b2g/chrome/content/content.css#87

When it comes to giving a very custom look to some html UI elements like buttons, 
you should try to override all rules. Here are the missing ones:

```
  background-image: none;
  border-radius: 0;
```

This behavior is non-optimal. There is some plans to make the styles being done without such custom CSS rules, but there is no ETA for that.

**Comment by Trux** [comment]
So basically i should load some kind of "normalize.css " before loading my custom css.

**Comment by mykmelez** [comment]
@Trux Yes, that seems like a reasonable solution until Gaia is changed to no longer load such styles.
