### ISSUE TITLE
b2g and gaia installed but add-on does not work

### ISSUE THREAD

**Issue by markrcote** [mozilla/r2d2b2g#566]
At the Montreal FirefoxOS App Day today, I tried to help someone who had problems installing the simulator add-on. He is running Firefox 21 under Windows Vista, installing the add-on from local disk.

The add-on took a long time to install--he got 3 unresponsive-script dialogs--but then ended with a success message. However the simulator never appeared in the Web Developer menu. When he tried running it directly from a resource URI, it loaded the page, but trying to start the simulator failed (the slider shifted to Running, but the cursor changed to a spinner when hovering over the control). I saw no interesting messages in the web console.

Interestingly, running b2g desktop from the command line worked fine, loading gaia with no problems. So the problem appears confined to the add-on.

**Comment by mykmelez** [comment]
We have reports like this occasionally, and we've found and fixed a few bugs that cause this over the last couple months. Do you know what version of the addon he tried? And are you still in touch with this person by any chance? I can help troubleshoot the problem if so.

(Note #580, which is a similar problem but seems Ubuntu-specific.)

**Comment by mykmelez** [comment]
@markrcote I suspect that he experienced one of the problems we've fixed since we released version 3.0/3.0.1. So it probably isn't worth tracking him down. But note that users experiencing issues may try the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)) to see if the issues are resolved. And we plan to publish a new stable release with those fixes in a few weeks.

**Comment by mykmelez** [comment]
I have closed this issue, since it isn't possible to diagnose it without being able to communicate with the person experiencing it. Nevertheless, I appreciate the report! And hope that we've already fixed the problem. Feel free to reopen if the person contacts you or someone else reproduces it, however!
