### ISSUE TITLE
Screenshot of device

### ISSUE THREAD

**Issue by marti1125** [mozilla/r2d2b2g#588]
Is possible to add a button for take screenshot of device (Keon)

**Comment by mykmelez** [comment]
It's possible, but it isn't necessary, since you can take a screenshot of the device by pressing its Home and Power buttons simultaneously. And that seems like a reasonable way to take screenshots, since it should be relatively easy to do so whenever appropriate and then transfer the screenshots to your computer via familiar mechanisms. Thus I would be cautious about adding such a feature to the Simulator unless it was a very common use case and proved to be quite cumbersome to do directly on the device.
