### ISSUE TITLE
nextCard is null

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#600]
Timestamp: 11/06/2013 23:07:31
Error: TypeError: nextCard is null
Source File: app://system.gaiamobile.org/js/cards_view.js
Line: 515

i can regenerate the problem:

open any app (preinstalled)
click home button
clear all the logs
Force the closure of the app in background

for me is only a message, this is generated because if you close the app there aren't any other app in background.i think this because:
try to pen 1 app & click home button, open another app & click home button (now we are 2 apps in background. NOW clean ALL the logs try to force the closure of 1 app. NO ERROR)

**Comment by mykmelez** [comment]
This seems like a Gaia issue rather than a Simulator issue, and since it doesn't affect usage of the Simulator by app developers, it isn't something we're likely to address in the Simulator. But you can report it in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
