### ISSUE TITLE
ReferenceError: asyncStorage is not defined

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#605]
Timestamp: 12/06/2013 00:05:48
Error: ReferenceError: asyncStorage is not defined
Source File: app://communications.gaiamobile.org/dialer/js/contacts.js
Line: 176

(my address book is EMPTY, i think is this the problem)
start the simulator
click on the call button & clear ALL the logs
try to digit any number >=3 (for example 123) & receive the error

**Comment by mykmelez** [comment]
Hi @stefanostatuti, thanks for reporting this problem! Individual messages in the Error Console, like this one, aren't necessarily a cause for concern. So we don't typically track each one.

But an empty address book is a concern, since the Contacts app advertises some activities, and we want developers to be able to test use of those activities in their apps. I suspect that problem is the existing issue #400. So I'm going to close this issue. But please reopen it if you think it's a different issue!
