### ISSUE TITLE
"use my current coordinates" doesn't work before push from Dashboard

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#652]
If I start the Simulator and then tell it to use my current coordinates for the geolocation simulation, it doesn't actually do so. Apparently this is because it notifies "r2d2b2g:geolocation-start", but SimulatorActor doesn't observe the notification because it hasn't been instantiated yet.

Once I push an app from the Dashboard, though, SimulatorActor gets instantiated, and a subsequent request to "use my current coordinates" succeeds.

I suppose we could work around this problem by having RemoteSimulatorClient send a ping to the server onClientReady. Although I'd like to figure out why SimulatorActor isn't instantiated until DebuggerServer receives a message for it. Perhaps that's intentional, perhaps it's a bug, but either way it would be good to know.

**Comment by nickdesaulniers** [comment]
indeed, the only thing logged in the console when current coords requested is `info: r2d2b2g: Current coordinates requested in shell, notifying Simulator` which happens [here](https://github.com/mozilla/r2d2b2g/blob/83983d38e85e5064009586ef1c3445465d590c32/prosthesis/content/shell.js#L59).  The "r2d2b2g:geolocation-start" event should be being observed by the [SImulatorActor](https://github.com/mozilla/r2d2b2g/blob/83983d38e85e5064009586ef1c3445465d590c32/prosthesis/content/dbg-simulator-actors.js#L21).

**Comment by nickdesaulniers** [comment]
when it works I see: `simulator actor created for a new connection`, which is not [printed](https://github.com/mozilla/r2d2b2g/blob/83983d38e85e5064009586ef1c3445465d590c32/prosthesis/content/dbg-simulator-actors.js#L15) when it does not work.

**Comment by nickdesaulniers** [comment]
One thing that is confusing is that in prosthesis/content/patch-remote-debugger.js is it saves the old version of RemoteDebugger.start, and modifies the property to call a new version.  But the thing is is that that code is never run (to my knowledge) and that RemoteDebugger [never had a start property](https://github.com/mozilla-b2g/gaia/blob/master/apps/system/js/remote_debugger.js#L8).

**Comment by ochameau** [comment]
We are patching the `shell.js`'s one over here:
http://mxr.mozilla.org/mozilla-b2g18/source/b2g/chrome/content/shell.js#946

**Comment by nickdesaulniers** [comment]
@mykmelez , sending the ping on clientReady does indeed fix this.  Who should I talk to about the globallyAdded actors not being initialized until initial communication is sent to the DebuggerServer? Probably @past?

**Comment by ochameau** [comment]
As far as I understood actors, they are loaded lazily:
http://mxr.mozilla.org/mozilla-central/source/toolkit/devtools/server/main.js#781

So that, SimulatorActor constructor won't be instanciated until we query one of its request.
That being said, we can pass an object to `DebuggerServer.addGlobalActor` instead of the function.
It will then be initialized on debugger server initialization.
But at the end, I think it makes sense to have an explicit request to start (and eventually stop) listening for events on the server side.
For example, if we land these actors to the device and a developer connects to it, he may not care about geolocation events until he opens a geolocation-related tool.

**Comment by past** [comment]
The server purposefully initializes registered actors when they receive their first message, since some actors can have an expensive startup pocess and then go unused until the server is restarted. This is exacerbated by the fact that actors can be provided by 3rd-party add-ons where we can't get the same quality guarantees.

The initial request idea that @ochameau mentioned is precisely how most of the existing actors operate, with the most common request name being "attach", since it indicates the client's interest and intent to communicate with the actor in the future. Such actors usually also respond to a "detach" request by performing any necessary cleanup.

**Comment by nickdesaulniers** [comment]
Thanks @past !  @ochameau , would you prefer the patch as is with a new issue added for attach/detech events, or have them rolled in with this patch?
