### ISSUE TITLE
Clearing App Cache

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#66]
Seems like apps don't have a separated cache (correct me if I am wrong) in B2G, which makes cleaning cache for just one app _hard_.

Some ideas:
- Clearing the cache when the user _updates_ an app. Might have unexpected results, as other apps that weren't updated will also be reset.
- An option to `Clear Cache on Launch`, similar to `JS Console`.
- Alternatives, like changing install flow (to give apps a new ID on install), experimenting.

What are your thoughts on that, @dangoor, @mykmelez ?

**Comment by dangoor** [comment]
Is this about all caches around an application, or specifically the "appcache" (in the "html5 application cache" sense)? The key thing I was thinking of was ensuring that application resources that have been saved for offline use in the appcache should be easy to purge and replace (because I've gathered that you generally need to change the manifest itself to force resources to reload).

**Comment by digitarald** [comment]
For this discussion this should include the whole set of caches (cached resources, app cache, local storage, indexeddb, etc). We might want to split up the automatic resource cache, who are easy to control with cache headers, from persistent offline-app-cache/local-storage/indexeddb), which are harder to control or flush.

**Comment by dangoor** [comment]
Right, I think it's better to provide support for clearing out the persistent data.

**Comment by mykmelez** [comment]
I wonder if recent changes by @rpl have resolved this issue.

**Comment by mykmelez** [comment]
Now that we have a Ctrl/Cmd-R shortcut for repackaging/reinstalling/restarting an app, we might consider a Shift-Ctrl/Cmd-R shortcut that also clears the cache (à la the same shortcut in the browser).
