### ISSUE TITLE
Simulator duplicates hosted apps on Windows 7

### ISSUE THREAD

**Issue by ldoubleuz** [mozilla/r2d2b2g#676]
**Version 4.0pre9 of the OS simulator on Firefox 23.0, Windows 7 64bit.**

I'm having an issue where having more than one hosted app in the simulator at a time causes all added apps in the simulator to be duplicates of the first app to be added. 

Essentially, when I add an app to the simulated phone environment using the Refresh button in the simulator addon UI, the first app I add will act as normally, but if I add another app in the same method, the second app appears to act like a duplicate of the first app, even though the name is correct.

I am only able to fix this by completely removing the apps from the simulated phone. However, adding apps will again cause all subsequent apps to be duplicates of the first app to be added.

For reference, I'm using the following two manifests: http://mozilla.github.io/app-components/slider/demo/manifest.webapp, and http://mozilla.github.io/app-components/tooltip/demo/manifest.webapp

Steps to reproduce:
- Add the tooltip app then the slider app in that order by clicking the Refresh button in the simulator addon UI.
- The Slider Demo and Tooltip Demo in the simulator should both act like the tooltip app.
- Remove both apps from the simulator using its simulated phone interface.
- Add the **slider** app then the tooltip app in that order by clicking the Refresh button in the simulator addon UI.
- The Slider Demo and Tooltip Demo in the simulator should both act like the slider app.

**Comment by sudheesh001** [comment]
WORKSFORME

#### Windows 7 Ultimate 64 bit

#### Windows 8

There are (1) warnings generated in the simulator addon when adding the manifest.webapp

**Comment by mykmelez** [comment]
I see this problem, but it's (somewhat) expected, since hosted apps must have unique origins, and those two manifests share the same origin (http://mozilla.github.io).

If those apps are intended to be installed into the Simulator, then they would need to expose their manifests at unique origins. Otherwise, there's not much the Simulator can do (at best, we can warn the user about the origin overlap), since the "unique origins" requirement is fundamental to Firefox OS.

cc: @potch, who might know if we can give these apps unique origins on GitHub.
