### ISSUE TITLE
Unable to connect to a particular app

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#690]
I can connect to all my other apps, but this one.  It gets started in the simulator, but the debugger in the dashboard never opens.  [Here's the app](https://github.com/nickdesaulniers/simulatorTestReceipt). cc @mykmelez

**Comment by nickdesaulniers** [comment]
I can connect to my other packaged apps.

**Comment by mykmelez** [comment]
cc: @ochameau

**Comment by mykmelez** [comment]
Hmm, I'm unable to reproduce. Whether I add the app as packaged, hosted, or generated, I can connect to it, see its console output, and see its scripts in the Debugger tab.

**Comment by rpl** [comment]
On an existent profile I use during development there was a registered
packaged app without an origin in its registered config object
(simulator.apps[appid]), so its generated manifestURL was
"undefined/manifest.webapp" and connectToApp wasn't able to resolve the app
from its invalid manifestURL.

In my case removing / add the app or installing a more recent generated
r2d2b2g.xpi to run the upgrade hook resolved the issue.

**Comment by mykmelez** [comment]
@rpl Ah, good idea!

I've seen that problem too, and I addressed it by updating the xkey validator to regenerate xkeys for upgrades from all versions prior to 3.0pre8 in 581dac2e1da490b218b98b2ed9870e91164a1749. I subsequently updated the version to 3.0pre9 in 9a2ed1d66dbb4af3c44f9b29e353cad3311dd016 because I wasn't sure we caught all such issues by 3.0pre3. (I'm still not sure we've caught all of them.)

@nickdesaulniers you might try deleting the app and readding it, which should fix the problem. Or do what @rpl suggested and install a XPI into the profile you're using for testing, since `make run` doesn't trigger the upgrade handler.

**Comment by mykmelez** [comment]
s/3.0pre8/3.0pre3/
s/3.0pre9/4.0pre9/

**Comment by mykmelez** [comment]
And @ochameau updated the validator to 4.0pre5dev in 51ccc65dc84fc22d532d160dd18270e8a52eb552. Obviously this is an ongoing problem that we need to get a handle on. :-(

**Comment by mykmelez** [comment]
@nickdesaulniers Are you still seeing this? If so, can you attach the _jetpack/r2d2b2g@mozilla.org/simple-storage/store.json_ file in your profile?

**Comment by nickdesaulniers** [comment]
Closing, since a reinstall fixed the issue.
