### ISSUE TITLE
Use new Releases feature for preview builds?

### ISSUE THREAD

**Issue by bkase** [mozilla/r2d2b2g#694]
See: https://github.com/blog/1547-release-your-software

It seems like it would be nice have the preview builds for the simulator available on Github Releases.

**Comment by mykmelez** [comment]
Hey, that looks really cool!

However, AMO has a [Beta Channel feature](https://addons.mozilla.org/en-us/developers/docs/policies/maintenance) that seems easier to integrate, since AMO takes care of generating the files that enable Firefox to automatically update users to the most recent preview build. I recently asked @kmaglione to fully review the Simulator, which he's going to do this week; after which we can set up a beta channel for it and start using the channel to push preview builds!

So I think we should pass on GitHub Releases for the time being and give the AMO Beta Channel a shot. But it's good to keep in mind in case the AMO Beta Channel doesn't meet our needs for some reason. And perhaps we can use it to release versions of libadb!
