### ISSUE TITLE
Console does not scroll with more content

### ISSUE THREAD

**Issue by es92** [mozilla/r2d2b2g#698]
Right now it is necessary to manually scroll down to new content. The console should scroll along with new content, if the console was already scrolled to the bottom.

If this is platform dependent, I'm on Firefox 22.0 on linux x64.

**Comment by mykmelez** [comment]
It isn't platform-dependent, but it does depend on the version of the console. Since you filed this 15 days ago, and we released the new version of the Simulator, 4.0, on July 11, only 8 days ago, I suspect you were using the previous version, 3.0, which had a different console in it.

The new console is accessible by pressing the Connect button next to an app, and it correctly scrolls with new content as long as you are scrolled to the bottom of the content when the new content comes in! So I'm going to close this issue on the assumption that it has been fixed; but please let us know if you experience the behavior with the new console as well!
