### ISSUE TITLE
B2G Desktop stacked on the "Based on Mozilla Technology" screen

### ISSUE THREAD

**Issue by blacharnia** [mozilla/r2d2b2g#719]
Reproduction path :
1. b2g-25.0a1.multi.win32.zip donwloaded and unzipped.
2. b2g.exe run

Result:

B2G Desktop stacked on the "Based on Mozilla Technology" screen

Same thing for b2g-25.0a1.en-US.win32 and b2g-18.0.multi.win32)
Env: Win7 x64

Happy to provide more details, if needed.

blacharnia

**Comment by mykmelez** [comment]
@blacharnia I'm sorry to hear about the problem! However, it sounds like a bug in B2G Desktop rather than a bug in the Simulator, which doesn't use the B2G Desktop 25 builds that you appear to be downloading and executing. In particular, it sounds like [bug 849755](https://bugzilla.mozilla.org/show_bug.cgi?id=849755). Based on the description in that bug report, there might be a workaround, although I haven't tried it: run b2g-bin.exe on a command line, passing it the path to the Gaia profile to use as the value of its "-profile" flag, i.e. something like:

```
b2g-bin.exe -profile C:\path\to\b2g\gaia\profile
```
