### ISSUE TITLE
Apps installed with the simulator dashboard don't appear on the phone until restarting

### ISSUE THREAD

**Issue by sole** [mozilla/r2d2b2g#729]
I clicked on 'Push' to install an app from the Dasboard onto the phone.

After a little while a message on the phone says it was installed. But I couldn't find it anywhere (this was the first app I installed).

I restarted the phone and then the app was there.

**Comment by mykmelez** [comment]
This sounds like #452, so I'm going to guess it is! But please reopen if it turns out to be a different problem with the same symptom!

**Comment by sole** [comment]
Yes, I'd say it sounds like #452. The Geeksphone I have got an update pretty much as soon as I turned it on, but the update brings the system to "just" 1.0.1.

But... why is #452 closed? If developers want to do apps for phones that people _use_ we need to be on 1.0.1
Is `adb shell "stop b2g && start b2g"` the interim solution?

**Comment by mykmelez** [comment]
#452 is closed because the bug is in B2G, not the Simulator; and the Simulator cannot work around the bug. The best thing the Simulator team can do is document the limitation, for example in the [Simulator docs on MDN](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator) (cc: @wbamberg for his consideration).

(FWIW, the B2G team can't do much more either, since they don't control device updates. Those are the responsibility of the operators. The best thing the B2G team can do is land the fix on the 1.0.1 branch and hope the operators update phones on that branch. But they decided not to do that back in March 6 over in [bug 842725, comment 9](https://bugzilla.mozilla.org/show_bug.cgi?id=842725#c9).)
