### ISSUE TITLE
How do I get a simulator with a custom Gaia version?

### ISSUE THREAD

**Issue by sole** [mozilla/r2d2b2g#733]
I am trying to _guess_ how to do that using the bits of information at #715 but no matter what I try I still get a simulator that launches a gaia built on the 26/27th of June.

What I've done is:
- cloned the repo
- then cd to the dir, `git submodule init`, `git submodule update`
- cd into `gaia`, `git fetch origin`
- checked out `v1-train` branch as it seemed the most recent one
- `cd ..`
- `make build`
- `make run`
- a new firefox instance opened, I opened the simulator dashboard and started it, and it's still the old Gaia, according to settings info

What am I doing wrong?

Help!! :cry:

**Comment by mykmelez** [comment]
> ```
> then cd to the dir, git submodule init, git submodule update
> ```

Note that you can combine the latter two steps into `git submodule update --init`.

> ```
> cd into gaia, git fetch origin
> checked out v1-train branch as it seemed the most recent one
> ```

The _origin_ remote is a fork of the Gaia central repository in this case, since I sometimes need to modify Gaia to work in the Simulator. I update _v1-train_ on it pretty regularly, although you happen to have pulled it right at the tail end of a three-week lull in updates as I focused on getting Simulator v4 out the door. I just updated the fork with upstream changes as of Wednesday, July 17, so you should get those changes if you `git checkout v1-train && git pull` again.

However, note that there are two downstream changes pending integration upstream, which I landed on two branches, [v1-train-883834](https://github.com/mykmelez/gaia/tree/v1-train-883834) and [battery-charging](https://github.com/mykmelez/gaia/tree/battery-charging) and then merged with _v1-train_ in an integration branch, [v1-train-integration](https://github.com/mykmelez/gaia/tree/v1-train-integration). So if you check out _v1-train_, you won't get those fixes. Therefore you should check out _v1-train-integration_ instead:

```
git checkout -b v1-train-integration origin/v1-train-integration
```

Then if you need a newer _v1-train_ than the one in my fork, add the central repo as another remote, fetch it, and merge its _v1-train_ into your local _v1-train-integration_ branch:

```
git remote add upstream git@github.com:mozilla-b2g/gaia.git
git fetch upstream
git checkout v1-train-integration
git merge upstream/v1-train
```

**Comment by sole** [comment]
Thanks for taking the time explaining this!

So basically any version of gaia that I check out in the gaia directory _should_ be used by the simulator, right?

I added the upstream remote and merged the latest changes into my local branch. And did make clean, build and run.

However, I might be doing something wrong, because the settings still say this build identifier is 20120626... something
![screen shot 2013-07-19 at 17 56 24](https://f.cloud.github.com/assets/5609/827025/6ef894f4-f094-11e2-81da-3d6a2c2f6e57.png)

**Comment by mykmelez** [comment]
> So basically any version of gaia that I check out in the gaia directory should be used by the simulator, right?

Right! After changing files in the gaia/ directory, you just have to `make profile` to build the changes. Also note that you can override Gaia settings/preferences without changing Gaia itself by modifying the files build/override-settings.json and build/override-prefs.js.

> However, I might be doing something wrong, because the settings still say this build identifier is 20120626... something

This is the B2G build identifier, not the Gaia one. I'm not sure how to find out the "version" of Gaia in the Simulator; I suspect it isn't exposed anywhere because it doesn't actually exist, i.e. there is no notion in Gaia of a version of the software.

**Comment by mykmelez** [comment]
Note that you should also `git pull` from the r2d2b2g/ directory to get the newer version of B2G (2013-07-17).

**Comment by sole** [comment]
Thank you so much for this info! It is sorely needed--will document it somewhere else.

Can I ask you something else: what does the profile exactly store?

**Comment by sole** [comment]
Also: I did what you said and effectively the B2G identifier changed to 17 of July. GREAT!

**Comment by mykmelez** [comment]
> Thank you so much for this info! It is sorely needed--will document it somewhere else.

cc: @wbamberg in case he has suggestions for where to document this!

@wbamberg this is definitely power-user info, since it presupposes that the user is able to clone a Git repo and build the project. But it isn't necessarily only for project contributors, so I'm not sure the project's [CONTRIBUTING.md](https://github.com/mozilla/r2d2b2g/blob/master/CONTRIBUTING.md) doc is the right place for it. See #715 for another power-user who similarly wants to run the Simulator with a custom Gaia version.

> Can I ask you something else: what does the profile exactly store?

The bulk of the profile is the core apps built into Gaia; they take up 29M of the 40M profile I just built from the tip of the trunk!

```
07-19 16:44 > du -shc addon/template/profile/*
124K    addon/template/profile/defaults
 88K    addon/template/profile/extensions
 64K    addon/template/profile/permissions.sqlite
10.0M   addon/template/profile/places.sqlite
 32K    addon/template/profile/places.sqlite-shm
 68K    addon/template/profile/places.sqlite-wal
104K    addon/template/profile/settings.json
 24K    addon/template/profile/user.js
 29M    addon/template/profile/webapps
 40M    total
```

(The other large chunk is places.sqlite, at 10M, which is actually an empty database with a bunch of preallocated space for performance. So Gaia apps really make up 29M of 30M, almost the whole profile!)

The rest of the files are common files in any XUL profile (i.e. the directory that a XUL application like Firefox and Thunderbird use to store user data). Although Gaia isn't a XUL application, it runs inside B2G, which is, so it lives in a profile directory. Some high-level info about profiles is in [this Firefox support doc](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data).

**Comment by sole** [comment]
THANK YOU SO MUCH!!! Extremely useful.

By the way--at this stage pretty much all developers that find bugs should become "power users" as you call them. It's the best way to help overworked simulator and gaia developers to test bugs without asking silly questions once and once and once again

Here's a well deserved :beer: for @mykmelez !!

**Comment by jryans** [comment]
@mykmelez: Probably fine to close this issue, since the question has been answered?

**Comment by sole** [comment]
Yes guys, sorry. Should have closed it myself. Will do it right now!
