### ISSUE TITLE
Feedback App

### ISSUE THREAD

**Issue by syssgx** [mozilla/r2d2b2g#79]
Feedback Application should indicate sending the info, and inform the user for completion of the communication.

**Comment by mykmelez** [comment]
That feedback app is a bit misleading, as it is provided by the default B2G/Gaia distribution, but I don't think the B2G/Gaia folks are actually monitoring feedback from these builds. We might actually want to remove or hide the app to avoid the impression that we're soliciting feedback through it.

Fortunately, you found the right way to give us feedback about the Simulator, which is to submit issues in this issue tracker!

**Comment by syssgx** [comment]
Good to know :)
So who do I contact for some more technical topics discussions? (i'd like to get involved with a topic).

**Comment by mykmelez** [comment]
For general discussion of technical topics related to the project, contact its team on the #openwebapps IRC channel on irc.mozilla.org and the [dev-webapps discussion forum](http://www.mozilla.org/about/forums/#dev-webapps)!

Also, FWIW, this particular issue with the Feedback app has been reported to the B2G team by a number of folks, including me, who used the Feedback app itself on a B2G testing phone to report it! So that team knows about it. :-)
