### ISSUE TITLE
Firefox OS Simulator since 4 is not working on Mac OS 10.9

### ISSUE THREAD

**Issue by elalecs** [mozilla/r2d2b2g#858]
The test is on Firefox 24, 25 and 27a1 and the simulator in the versions 4 and 5pre6

Sometimes it works but most all the time it fails to start

The log error: http://pastebin.com/PRwKPufK

**Comment by jeena** [comment]
Same here, I can open the index page but when I press "Connect" or "Refresh" it crashes like it happens for @elalecs

**Comment by ochameau** [comment]
We are facing some crashes, happening only on MacOS Maverick, when starting the simulation process.
More info about this failure over here:
  https://bugzilla.mozilla.org/show_bug.cgi?id=928168
I'm going to close this github bug as this issue is tracked on bugzilla. I suggest you to track bugzilla if you want updates about this crash.

Thanks for the report.
