### ISSUE TITLE
document simulator keyboard shortcuts

### ISSUE THREAD

**Issue by syssgx** [mozilla/r2d2b2g#87]
I think it would be useful to have a "desktop keyboard map", so users know which buttons does what.
For example, is there an Escape-Back button? Which one? (apparently, Esc is not the Back one).

**Comment by mykmelez** [comment]
We used to have a short text on the dashboard explaining the two most common keyboard shortcuts (Home to go home and Esc to go back); but we removed that because we added a visible Home button to the interface and the ability to "go back" was removed from B2G, so there is no longer much utility to explaining the keyboard shortcuts.

It would be useful to give the Home button a tooltip that references the keyboard shortcut, and I tried to do that when I implemented the Home button, but adding a tooltip caused B2G to crash when it tried to display it. (I still need to file a B2G bug about this.)

It might also be useful to add a keyboard shortcut reference to the Help section of the manager, even though the other shortcuts are not as useful to app developers testing their apps, since developers like shortcuts. :-) Besides the Home, there's also Arrow Up and Arrow Down to raise/lower volume and End to lock the screen.

@dangoor what do you think?

**Comment by syssgx** [comment]
how is the greater window UI implemented? with HTML and CSS?

**Comment by mykmelez** [comment]
The Manager tab is implemented in HTML (and CSS, JS, etc.). The Simulator window is implemented in XUL, although the XUL part is a relatively minimal "shell", and Gaia's interface is entirely HTML.

**Comment by dangoor** [comment]
That sounds like a great idea, @mykmelez

**Comment by mykmelez** [comment]
Ok, I have implemented this in commit 757d562f17ed73b458816ec4162e823879c2e679.
