### ISSUE TITLE
Firefox OS simulator doesn't detect devices on Windows XP Home

### ISSUE THREAD

**Issue by Loirooriol** [mozilla/r2d2b2g#892]
Firefox OS simulator doesn't detect devices on Windows XP Home, because it doesn't have doesn't have tasklist.exe

The problem is solved downloading it from http://www.computerhope.com/download/winxp.htm and putting it in Windows\System32 folder.

Maybe the add-on could include it, it's only 70KB.

**Comment by jryans** [comment]
I think it's unlikely that we'd bundle random EXEs with the addon. As I user, I certainly would not want a Simulator installing strange EXEs in my Windows folder.

If that's what is needed for Windows XP Home to work, I think we just won't be able to support it at this time.

Out of curiosity, does the same issue happen with the [newest simulators](https://ftp.mozilla.org/pub/mozilla.org/labs/fxos-simulator/), like 1.5?

**Comment by Loirooriol** [comment]
Oh, I didn't meant Simulator should install it in Windows folder, but that it could include it (in Simulator folder) and run this one if necessary.

If not, I think that Simulator should handle this case properly.

In `r2d2b2g@mozilla.org\resources\r2d2b2g\lib\adb.js` (line 240):

```
if (platform === "WINNT") {
  ps = "C:\\windows\\system32\\tasklist.exe";
  args = [];
} else {
  args = ["aux"];
  let psCommand = "ps";

  let paths = env.PATH.split(':');
  let len = paths.length;
  for (let i = 0; i < len; i++) {
    let fullyQualified = file.join(paths[i], psCommand);
    if (file.exists(fullyQualified)) {
      ps = fullyQualified;
      break;
    }
  }
  if (!ps) {
    debug("Error: a task list executable not found on filesystem");
    deferred.resolve(false); // default to restart adb
    return deferred.promise;
  }
}
```

In case of Windows XP Home, I think the following code should run:

```
    debug("Error: a task list executable not found on filesystem");
    deferred.resolve(false); // default to restart adb
    return deferred.promise;
```

But instead, since it's windows, it assumes that `C:\windows\system32\tasklist.exe` does exist.

**Comment by jryans** [comment]
Ah, okay. This is part of the older **Firefox OS 1.1 Simulator** that is no longer maintained.

The 1.2+ simulators do not contain the above file because all ADB stuff is handled separately. The newer addons are used via the [App Manager](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Using_the_App_Manager).

With the App Manager, you can run ADB manually or use the [ADB helper addon](https://developer.mozilla.org/en-US/Firefox_OS/Using_the_App_Manager#Adb_Helper_Add-on) to do this for you. It looks like the ADB helper has the same flaw you've found here though.

We also have a more [experimental ADB addon](https://ftp.mozilla.org/pub/mozilla.org/labs/fxos-simulator/adb-helper/adbhelper-windows.xpi) which does not appear to use `tasklist` which might work for you, but again this is only meant for use with the App Manager and FxOS 1.2+.

I have filed a bug about the [ADB helper](https://bugzilla.mozilla.org/show_bug.cgi?id=1006844) on this issue.

**Comment by AprilMorone** [comment]
Not sure as I have temporarily had to step away from testing the Firefox
OS.  But, I soon will check on that later this week, if possible.

**Comment by AprilMorone** [comment]
Thank you for having filed a bug on this issue.

**Comment by Loirooriol** [comment]
Replacing `_isAdbRunning` with the following code fixes the problem:

```
_isAdbRunning: function() {
  let deferred = Promise.defer();

  let ps, args;
  let platform = Services.appinfo.OS;
  if (platform === "WINNT") {
    ps = "C:\\windows\\system32\\tasklist.exe";
    args = [];
  } else {
    args = ["aux"];
    let psCommand = "ps";

    let paths = env.PATH.split(':');
    let len = paths.length;
    for (let i = 0; i < len; i++) {
      let fullyQualified = file.join(paths[i], psCommand);
      if (file.exists(fullyQualified)) {
        ps = fullyQualified;
        break;
      }
    }
  }

  if (ps) try {

    let buffer = [];

    subprocess.call({
      command: ps,
      arguments: args,
      stdout: function(data) {
        buffer.push(data);
      },
      done: function() {
        let lines = buffer.join('').split('\n');
        let regex = (platform === "WINNT") ? psRegexWin : psRegexNix;
        let isAdbRunning = lines.some(function(line) {
          return regex.test(line);
        });
        deferred.resolve(isAdbRunning);
      }
    });

    return deferred.promise;

  }catch(err){
    if(err.name !== "NS_ERROR_FILE_NOT_FOUND") throw err;
  }

  debug("Error: a task list executable not found on filesystem");
  deferred.resolve(false); // default to restart adb
  return deferred.promise;

},
```
