### ISSUE TITLE
Kill Simulator when Firefox closes

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#90]
Currently the process stays alive when the manager or browser closes, which causes problems.

We could also close the Simulator only when the browser closes, but attaching its life to the Manager tab seems to the better paradigm.

Thoughts? @dangoor @mykmelez

**Comment by dangoor** [comment]
I don't have a strong feeling on this one. I have left the Simulator open after closing the Manager before, but that hasn't bothered me much.

I do think you make a good point though and we should either close it when the browser closes or when the Manager closes. I think I lean slightly to close it when the browser closes, because I'm weird and just used the "firefoxos stop" command when I noticed that I still had it running :)

**Comment by shavounet** [comment]
I can't say I spent much time on this, so maybe this is not relevant, but since I restarted Firefox (18, win7 x64) I can't start the simulator anymore : when clicking on the switch nothing happens (except the animation). 

The only clue I have is that the dashboard was already opened when I started Firefox with the switch on "Running" (I enabled the auto tab saving). I haven't tried yet reinstalling the addon.

**Comment by mykmelez** [comment]
@shavounet Try checking the Task Manager to see if you have a _b2g-bin.exe_ process running. If so, kill it, then see if you can start the simulator again.

(It might also be possible for a _plugin-container.exe_ process to cause this problem, although I'm not sure about that, and those processes might be for Firefox itself, in which case killing them will cause plugins running in those processes to crash.)

**Comment by shavounet** [comment]
No _b2g-bin.exe_ never (at Firefox start & after clicking on the simulator switch). No _plugin-container.exe_ either (I don't use any plugin :-) ). The native web console does not show anything.

**Comment by mykmelez** [comment]
@shavounet Yesterday's 0.7 update fixed some issues on Windows. You might try [updating to it](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi) and see if it fixes your problems. Also try restarting your computer to see if that makes a difference.

**Comment by shavounet** [comment]
My addon isn't yet up-to-date but I managed to start the simulator ;) Thanks to yesterday's Mozilla Hacks blog post I noticed the "Firefox OS Simulator" in the Dev Tools menu. When starting the simulator using this (or the command line), all works fine, but when using a previously opened tab or a bookmark, the manager won't be able to start the simulator.

It may seem obvious, but I may not be the only one to make this mistake ;)
