### ISSUE TITLE
Dashboard version and Github version of r2d2b2g

### ISSUE THREAD

**Issue by syssgx** [mozilla/r2d2b2g#94]
With reference to #84 , the Simulator Dashboard should clearly make visible which build it's currently using. At the same time, the github page should indicate the newest build version. This will help everyone to know if new commits are about to be deployed and how new their r2d2b2g is.

**Comment by mykmelez** [comment]
We're going to move distribution from GitHub/ftpmo to AMO in the very near future. At that point, there will be no confusion about whether or not you are on the latest version, because Firefox and AMO will work together to keep you up-to-date! And if you still really need to know what version you are running, the Add-ons Manager will tell you, just as it does for other addons.

So the solution to these problems is really to move distribution to AMO!

**Comment by syssgx** [comment]
ok :)
